### ISSUE TITLE
Posting with Feign Client and x-www-form-urlencoded broken after 2020.0.4 update

### ISSUE THREAD

**Issue by apiatti** [spring-cloud/spring-cloud-openfeign#646] opened 2021-12-13 15:47 UTC
**Describe the bug**
Running a `POST` using  `'_application/x-www-form-urlencoded_'` causes the POST body to be completely empty. The issue is fixed by simply downgrading the Spring Cloud Version to `2020.0.3`. 

**Sample**

```
package ch.example.app;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.util.MultiValueMap;
import org.springframework.web.bind.annotation.PostMapping;

@FeignClient(name = "${security.idp.auth.name}", url = "${security.idp.auth.url}")
public interface IdpFeignClient {

    @PostMapping(consumes = "application/x-www-form-urlencoded")
    AuthenticationTokenDto getAuthenticationToken(MultiValueMap<String, ?> params);

}
```

Causes the `POST` body to be empty. Adding `org.springframework.web.bind.annotation.RequestBody` on the parameter doesn't fix the issue. What solves it though, is only downgrading to Spring Cloud Version `2020.0.3`. 
Any suggestions here on how to properly send this type of POST using `2020.0.4`?

**Comment by OlgaMaciaszek** [comment] 2021-12-15 12:17
@apiatti Thanks for submitting the issue. Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-12-22 12:20
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-02-04 01:06
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-02-04 01:06 UTC
Labels: waiting for feedback, feedback-reminder
