### ISSUE TITLE
openFeign2.1.1.RELEASE Custom Encoder not working

### ISSUE THREAD

**Issue by fengshuzi** [spring-cloud/spring-cloud-openfeign#186] opened 2019-05-21 09:41 UTC
Question

when I  use openFeign 2.1.1.RELEASE  , my custom encoder not working 

Bug report
details about pom.xml
```
    <properties>

        <spring-cloud.version>Greenwich.SR1</spring-cloud.version>

      <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
    </properties>
```

Enhancement
```
        <spring-cloud.version>Finchley.RELEASE</spring-cloud.version> 
```
it worked!

**Comment by spencergibb** [comment] 2019-06-03 14:42
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-06-10 14:46
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-17 14:46
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-17 14:46 UTC
Labels: feedback-reminder, waiting for feedback
