### ISSUE TITLE
Feign Client Integer RequestParam

### ISSUE THREAD

**Issue by arpita012020** [spring-cloud/spring-cloud-openfeign#780] opened 2022-11-03 13:47 UTC

**Comment by OlgaMaciaszek** [comment] 2023-03-07 17:48
@arpita012020 if you would like us to look at your issue please provide an issue description, including the steps to reproduce, the expected result and the actual result.

**Comment by spring-cloud-issues** [comment] 2023-03-14 17:52
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-03-21 17:52
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-03-21 17:52 UTC
Labels: waiting for feedback, feedback-reminder
