### ISSUE TITLE
 executing the original request 

### ISSUE THREAD

**Issue by klutz-he** [spring-cloud/spring-cloud-openfeign#654] opened 2021-12-28 09:00 UTC
1. `spring.cloud.loadbalancer.retry.maxRetriesOnSameServiceInstance`=1
2.service instances count is 1，

result: Service instance was not resolved, executing the original request

i think in this case , shouldn't executing the original request

**Comment by OlgaMaciaszek** [comment] 2022-01-14 16:15
Hello, @klutz-he , please provide a detailed description of the issue, including the steps necessary to reproduce the issue, the expected result and the actual result. Also, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2022-02-04 01:06
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-02-04 01:06 UTC
Labels: waiting for feedback

**Comment by oliverlockwood** [comment] 2023-03-01 14:59
For posterity: this is possibly related to #650 and the newly-related #840.
