### ISSUE TITLE
Trying to communicate between services - java.net.SocketException: Invalid argument

### ISSUE THREAD

**Issue by gustavomr** [spring-cloud/spring-cloud-openfeign#800] opened 2022-12-07 15:16 UTC
I'm trying to communicate between services using OpenFeign and getting this error on microservice that are receiving the request:

2022-12-06 22:30:26.634 ERROR 6352 --- [o-8081-Acceptor] org.apache.tomcat.util.net.NioEndpoint   : Error setting socket options

java.net.SocketException: Invalid argument
    at java.base/sun.nio.ch.Net.setIntOption0(Native Method) ~[na:na]
    at java.base/sun.nio.ch.Net.setSocketOption(Net.java:455) ~[na:na]
    at java.base/sun.nio.ch.Net.setSocketOption(Net.java:393) ~[na:na]
    at java.base/sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:280) ~[na:na]
    at java.base/sun.nio.ch.SocketAdaptor.setIntOption(SocketAdaptor.java:247) ~[na:na]
    at java.base/sun.nio.ch.SocketAdaptor.setSoLinger(SocketAdaptor.java:285) ~[na:na]
    at org.apache.tomcat.util.net.SocketProperties.setProperties(SocketProperties.java:219) ~[tomcat-embed-core-9.0.55.jar:9.0.55]
    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:495) ~[tomcat-embed-core-9.0.55.jar:9.0.55]
    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:78) ~[tomcat-embed-core-9.0.55.jar:9.0.55]
    at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:149) ~[tomcat-embed-core-9.0.55.jar:9.0.55]
    at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

Using macOS Monterrey 12.6, JDK 17, Spring boot 2.5.7 and Spring Cloud 2020.0.3. Tried to update to JDK 19, 2.6.1 and 2021.0.5 and got same errors. I also tried to use RestTemplate instead of OpenFeign.

**Comment by OlgaMaciaszek** [comment] 2023-03-07 17:52
Hello, @gustavomr. I do not see anything referring to a Spring Cloud OpenFeign method in the provided stacktrace.  If you want us to take a closer look, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2023-03-14 17:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-03-21 17:57
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-03-21 17:57 UTC
Labels: waiting for feedback, feedback-reminder
