### ISSUE TITLE
@FeignClient properties are not interpolated correcty

### ISSUE THREAD

**Issue by aaronjwhiteside** [spring-cloud/spring-cloud-openfeign#262] opened 2019-12-12 01:03 UTC
**Describe the bug**
Properties are not interpolated correcty, for example:
```java
@FeignClient(....., url = "${my.feign.client.url}") ...
```

and in `application.properties` if we define:
```
# for backwards compatibility
my.feign.client.url=${legacy.property.name} 
```

This results in:

```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'my.feign.client.url' in value "http://${legacy.property.name}"
```
Or an error while trying to make requests with the client because the URL is wrong.. 

This seems to be due to:

https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java#L108-L110

The workaround to this is to define the property in `application.properties` as:
```
my.feign.client.url=#{'${legacy.property.name}'}
```

**Comment by OLPMO** [comment] 2019-12-12 13:48
Could you provide a minimal demo to reproduce the bug?

**Comment by spencergibb** [comment] 2019-12-16 15:45
I don't think it ever worked did it?

**Comment by spring-issuemaster** [comment] 2019-12-23 15:49
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-12-30 15:47
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-12-30 15:47 UTC
Labels: feedback-reminder, waiting for feedback
