### ISSUE TITLE
@SpringQueryMapper Unable to get parent class attribute.

### ISSUE THREAD

**Issue by FatTigerWang** [spring-cloud/spring-cloud-openfeign#141] opened 2019-03-07 05:12 UTC
example 1:
``` 
public class PageParameter {

  private int pageSize = 10;

  private int pageNumber = 1;

  public int getPageSize() {
    return pageSize;
  }

  public void setPageSize(int pageSize) {
    this.pageSize = pageSize;
  }

  public int getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(int pageNumber) {
    this.pageNumber = pageNumber;
  }
}

public class QueryModel extends PageParameter {

}

public interface QueryFeign {

  @GetMapping("/query")
  String get(@SpringQueryMap QueryModel query);
}
```
expected:[QueryFeign#get] ---> GET http://xxxxxx/query?pageNumber=1&pageSize=10 HTTP/1.1
actual:[QueryFeign#get] ---> GET http://xxxxxx/query HTTP/1.1

example 2:
``` 
public class PageParameter {

  private int pageSize = 10;

  private int pageNumber = 1;

  public int getPageSize() {
    return pageSize;
  }

  public void setPageSize(int pageSize) {
    this.pageSize = pageSize;
  }

  public int getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(int pageNumber) {
    this.pageNumber = pageNumber;
  }
}

public interface QueryFeign {

  @GetMapping("/query")
  String get(@SpringQueryMap PageParameter query);
}
```
expected:[QueryFeign#get] ---> GET http://xxxxxx/query?pageNumber=1&pageSize=10 HTTP/1.1
actual:[QueryFeign#get] ---> GET http://xxxxxx/query?pageNumber=1&pageSize=10 HTTP/1.1

**Comment by FatTigerWang** [comment] 2019-03-07 05:15
Version:Greenwich.RELEASE

**Comment by ryanjbaxter** [comment] 2019-03-07 21:12
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by FatTigerWang** [comment] 2019-03-08 01:37
sorry,that's too much trouble.
can you give the basic judgments or suggestions based on my description?

**Comment by ryanjbaxter** [comment] 2019-03-08 01:44
No because your description is inadequate for me to have any idea what is happening

**Comment by FatTigerWang** [comment] 2019-03-08 01:47
wait a moment, I will provide the github project

**Comment by spring-issuemaster** [comment] 2019-03-18 14:35
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-03-25 14:35
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-03-25 14:35 UTC
Labels: feedback-reminder, waiting for feedback
