### ISSUE TITLE
POST: RequestBody + PathVariable

### ISSUE THREAD

**Issue by elabi3** [spring-cloud/spring-cloud-openfeign#86] opened 2018-11-22 17:23 UTC
Hi,

I have an issue:

**Version**

2.0.2.RELEASE

**Issue**

POST request: RequestBody + PathVariable

I have services with:

RequestBody - works fine!
PathVariable  - works fine!

but when I have both together, the PathVariable is not beign replace in the url.

**Example**

  @PostMapping(
    value = "/myReq/{path1}/anotherThing",
    consumes = {"application/json"}
  )
  ResponseEntity<String> postCall(
    @RequestHeader("Authorization") String accessToken,
    @Valid @RequestBody Object obj,
    @Valid @PathVariable("path1") String path1),
    @Valid @RequestParam(value = "par1", required = false) String par1,
  );

Url will be like: localhost:8080/myReq/{path1}/anotherThing/?par1=test but not replacing the path1

Thanks,

**Comment by ryanjbaxter** [comment] 2018-11-27 17:45
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2018-12-04 17:45
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-12-11 17:46
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-12-11 17:46 UTC
Labels: feedback-reminder, waiting for feedback
