### ISSUE TITLE
Remove or disable WARN logger when use url inside @FeignClient

### ISSUE THREAD

**Issue by Ferioney** [spring-cloud/spring-cloud-openfeign#508] opened 2021-03-11 11:07 UTC
**Describe the bug**
Spring Cloud Hoxton.SR10
Spring Cloud OpenFeign 2.2.7
Spring Cloud LoadBalancer 2.2.7

I use `url` inside FeignClient and Spring Cloud LoadBalancer (with Spring Retry):
```
@FeignClient(name = "local",
        url = "http://localhost:8113")
```

and I have two log records:
```
2021-03-11 12:59:29 WARN  RoundRobinLoadBalancer:143 - No servers available for service: localhost
2021-03-11 12:59:29 WARN  FeignBlockingLoadBalancerClient:103 - Service instance was not resolved, executing the original request
```

But when I use `url` in the client, usually I know that I don't have a service instance for these requests  and I don't need these `warn` records.

[warn RetryableFeignBlockingLoadBalancerClient](https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/RetryableFeignBlockingLoadBalancerClient.java#L135)
[warn RoundRobinLoadBalancer](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java#L96)

**Comment by OlgaMaciaszek** [comment] 2021-03-16 13:49
@Ferioney, thanks for reporting this. It seems to be a duplicate of https://github.com/spring-cloud/spring-cloud-openfeign/issues/494, though. There's already a fix that will be available in SC OpenFeign 2.2.8.

**Closed by OlgaMaciaszek** 2021-03-16 13:49 UTC
Labels: waiting-for-triage
