### ISSUE TITLE
Issues with @EnableFeignClients(basePackages) scanning in Spring cloud version Finchley.RC1

### ISSUE THREAD

**Issue by ravireddy76** [spring-cloud/spring-cloud-openfeign#23] opened 2018-05-24 14:55 UTC
Hi;
I'm getting issue with @enablefeignclients(basePackages) scanning in Spring cloud version Finchley.RC1;

Getting runtime exception saying that beans are not registered, Basically @enablefeignclients(basePackages = {"com.xxx.aa", "com.yyy.bb"}) are not scanning the packages and beans not getting registered.I'm getting base package beans classes from dependency artifacts.

It will great help if you guys provide a feasible solution or let us know in which version this issues can be solved.

The above issue used to work in spring cloud version 'Finchley.M5' before spring cmade have changes in feign client.

Thanks
Ravi

**Comment by ryanjbaxter** [comment] 2018-05-24 20:51
Without a way to reproduce the problem  it is going to be hard to help.  If you cant provide the actual code than maybe you can create a new project that reproduces the problem and attach that.

**Comment by Alos** [comment] 2019-01-02 20:20
We have run into this issue. A Feign client build in our JAR with the regular `@EnableFeignClients` annotation works. 

If we move the client to another JAR, add it as a dependency and then try to use the `@EnableFeignClients(basePackages=....)` we get an error indicating that there is a problem with one of the `@PathVariables` having a empty param 0. 

I will try to create a small project to reproduce the issue.

**Comment by spring-issuemaster** [comment] 2019-01-16 23:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-01-16 23:42 UTC
Labels: feedback-reminder, waiting for feedback
