### ISSUE TITLE
Do input and output parameters support generics?   

### ISSUE THREAD

**Issue by 15168326318** [spring-cloud/spring-cloud-openfeign#723] opened 2022-06-28 08:56 UTC
spring cloud ：Hoxton.SR12

@PostMapping("/user/add")
   RpcResult\<String\> add(@RequestBody RpcRequest\<UserAddDTO\> addDTO);

**Comment by 15168326318** [comment] 2022-06-28 08:57
@PostMapping("/user/add")
   RpcResult<String> Integer add(@RequestBody RpcRequest<UserAddDTO> addDTO);

}

**Comment by 15168326318** [comment] 2022-06-28 09:00
Call failed

**Comment by OlgaMaciaszek** [comment] 2022-09-05 13:56
Hello, @15168326318 `Hoxton.SR12` has not been supported for a long time. Please upgrade to a supported version (`2021.1.4`). If the issue still persists, please provide a description of the issue, including steps to reproduce, the expected result and the actual result. Also, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2022-09-12 13:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-09-19 13:57
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-09-19 13:57 UTC
Labels: waiting for feedback, feedback-reminder
