### ISSUE TITLE
how to add a json  header like userInfo: {"permissions":[]}  can not be create by Expressions

### ISSUE THREAD

**Issue by Iam95a** [spring-cloud/spring-cloud-openfeign#682] opened 2022-02-23 03:28 UTC
**Is your feature request related to a problem? Please describe.**
when i use requestInterceptor,i add a header like 
userInfo:{"permissions":[]}
and then will went exception
if i have to transform this param ,how i resovled it;

**Comment by OlgaMaciaszek** [comment] 2022-02-25 12:17
Hello, @Iam95a  please provide a more detailed description of the issue, including steps to reproduce, expected result and actual result. Also, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2022-03-04 12:20
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-03-11 12:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-03-11 12:20 UTC
Labels: waiting for feedback, feedback-reminder
