### ISSUE TITLE
Create non-blocking `SpringDecoder`.

### ISSUE THREAD

**Issue by fanticat** [spring-cloud/spring-cloud-openfeign#235] opened 2019-10-22 09:22 UTC
spring-boot-autoconfigure 2.2.0 change HttpMessageConverters auto configure with condition "NoReativeWebApplicationCondition", so when use openfeign to decode response, there will throws HttpMessageConverters not available exception, could you please add a HttpMessageConverters bean auto configure in openfeign configuration?

**Comment by weihai4099** [comment] 2019-12-02 02:26
It's happended when I update spring cloud version to Hoxton.RELEASE. And Greenwich.SR4 is ok.

**Comment by vicliu624** [comment] 2019-12-18 07:15
I am faced with the same problem with you


```
@Configuration
public class FeignResponseDecoderConfig {
    @Bean
    public Decoder feignDecoder() {

        ObjectFactory<HttpMessageConverters> messageConverters = () -> {
            HttpMessageConverters converters = new HttpMessageConverters();
            return converters;
        };
        return new SpringDecoder(messageConverters);
    }
}
```

**Comment by spencergibb** [comment] 2020-01-13 21:56
I am unable to reproduce the error.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spencergibb** [comment] 2020-01-13 22:04
The above is a workaround. `HttpMessageConverter`'s are blocking and will cause a webflux application to break. `HttpMessageReader` is the non-blocking equivalent.

**Comment by AlexTo** [comment] 2020-01-16 06:04
@spencergibb can you give some code example? I can't get feign to work even with @vicliu624 code

**Comment by AlexTo** [comment] 2020-01-16 06:07
Ah ok, @vicliu624 code does work but I have to declare both Encoder and Decoder like this 
``
private ObjectFactory<HttpMessageConverters> messageConverters = HttpMessageConverters::new;

    @Bean
    Encoder feignFormEncoder() {
        return new SpringFormEncoder(new SpringEncoder(messageConverters));
    }

    @Bean
    Decoder feignFormDecoder() {
        return new SpringDecoder(messageConverters);
    }
}
```

**Comment by rainmanhhh** [comment] 2020-04-23 02:41
5 months passed. any progress?

**Comment by spencergibb** [comment] 2020-04-23 02:51
No

**Comment by thewaychung** [comment] 2020-04-27 03:00
Using above workaround would cause performance issue: response time increase from 7ms to 30ms on the same FeignClient request path.

**Comment by Sbwillbealier** [comment] 2020-05-11 01:56
> Ah ok, @vicliu624 code does work but I have to declare both Encoder and Decoder like this
> 
> ```
> private ObjectFactory<HttpMessageConverters> messageConverters = HttpMessageConverters::new;
> 
>     @Bean
>     Encoder feignFormEncoder() {
>         return new SpringFormEncoder(new SpringEncoder(messageConverters));
>     }
> 
>     @Bean
>     Decoder feignFormDecoder() {
>         return new SpringDecoder(messageConverters);
>     }
> }
> ```

I use the following code to solve "feign.codec.EncodeException: "：
`    private ObjectFactory<HttpMessageConverters> messageConverters = HttpMessageConverters::new;

    /**
     * @return
     */
    @Bean
    Encoder feignEncoder() {
        return new SpringEncoder(messageConverters);
    }

    /**
     * @return
     */
    @Bean
    Decoder feignDecoder() {
        return new SpringDecoder(messageConverters);
    }`

**Comment by fanticat** [comment] 2020-06-29 01:09
> 5 months passed. any progress?

I have replaced the openfeign for [reactive feign](https://github.com/Playtika/feign-reactive) which is not blocking, it's working fine for me.

**Comment by OlgaMaciaszek** [comment] 2024-09-27 15:44
WebFlux support in SC OF is not planned. For reactive stack, we suggest using Spring Interface Clients instead. See docs: https://docs.spring.io/spring-cloud-openfeign/reference/4.2-SNAPSHOT/spring-cloud-openfeign.html#reactive-support . Closing as not planned.

**Closed by OlgaMaciaszek** 2024-09-27 15:44 UTC
Labels: closeable
