### ISSUE TITLE
Request Parameter Empty Set translated as "null"

### ISSUE THREAD

**Issue by sergio-marshmallow** [spring-cloud/spring-cloud-openfeign#305] opened 2020-03-09 18:31 UTC
**Describe the bug**

When an empty set is provided in the request parameters it gets translated as `null`

**Sample**

```java
 @GetMapping(value = QUOTES, produces = APPLICATION_JSON_VALUE)
 Set<Quote> getQuotes(@RequestParam(QUOTE_IDS) final Set<UUID> quoteIds);
```
request:

http://quoting-service/quotes?ids=null

**Comment by StefanTirea** [comment] 2020-03-24 08:59
When sending an empty String Set, the receiver gets this: {"null"}.

**Comment by OlgaMaciaszek** [comment] 2020-04-15 15:30
@sergio-marshmallow thanks for reporting it. Was able to reproduce this.

**Comment by sergio-marshmallow** [comment] 2020-04-15 15:32
@olegz thanks for looking into this 🙂

**Comment by OlgaMaciaszek** [comment] 2020-04-15 16:43
Caused by [this code](https://github.com/OpenFeign/feign/blob/187cba9c5d13335f3119cb4d778416c1b8c742d8/core/src/main/java/feign/template/Expressions.java#L155-L158).

**Comment by OlgaMaciaszek** [comment] 2020-04-15 18:20
@sergio-marshmallow since the issue is directly related to how Feign handles expanding iterable values and is not specific to how Spring annotations are handled, this should probably be opened in https://github.com/OpenFeign/feign, though.

**Comment by StefanTirea** [comment] 2020-04-18 10:43
@OlgaMaciaszek thank you for looking into this. I checked the OpenFeign Repo and they came to the same conclusion 12 days ago. They are working on fix and should be [merged](https://github.com/OpenFeign/feign/pull/1200) in the near future.

**Closed** 2020-04-22 08:59 UTC
Labels: bug, closeable, feedback-provided
