### ISSUE TITLE
MicrometerCapability bean not being created

### ISSUE THREAD

**Issue by johnnywiller** [spring-cloud/spring-cloud-openfeign#881] opened 2023-07-27 15:32 UTC
**Describe the bug**
Feign metrics do not appear:
```
"feign.Client",
"feign.Client.http_response_code",
"feign.Feign",
"feign.codec.Decoder",
"feign.codec.Decoder.response_size",
```
Reason:
`org.springframework.cloud.openfeign.FeignClientsConfiguration.MicrometerConfiguration#micrometerCapability` is not being created because it can't find a `MeterRegistry`. Report shows 
```
   FeignClientsConfiguration.MicrometerConfiguration#micrometerCapability:
      Did not match:
         - @ConditionalOnBean (types: io.micrometer.core.instrument.MeterRegistry; SearchStrategy: all) did not find any beans of type io.micrometer.core.instrument.MeterRegistry (OnBeanCondition)
```
The weird is, I have everything on classpath `spring-boot-starter-actuator`, `feign-micrometer` and `spring-cloud-starter-openfeign`, and in fact a `SimpleMeterRegistry` is being created through `org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleMetricsExportAutoConfiguration#simpleMeterRegistry`.

To solve the issue I needed to add a bean myself:
```
    @Bean
    public SimpleMeterRegistry simpleMeterRegistry(Clock clock) {
        return new SimpleMeterRegistry(SimpleConfig.DEFAULT, clock);
    }
```
With that everything works fine.

**Sample**
Simple app, a feign client, a config for importing `@Import(FeignClientsConfiguration.class)` (btw is that necessary?) :
```
@FeignClient(value = "numbersapi.com", url = "numbersapi.com")
public interface NumberFeignClient {
    @GetMapping("/{number}")
    String test(@PathVariable("number") int number);
}

@Configuration
@Import(FeignClientsConfiguration.class)
public class RegistryConfig2 {}


@Configuration
public class RegistryConfig {
// removing this bean makes it not work anymore    
@Bean
    public SimpleMeterRegistry simpleMeterRegistry(Clock clock) {
        return new SimpleMeterRegistry(SimpleConfig.DEFAULT, clock);
    }
}

@RestController
public class WebController {
    private final NumberFeignClient numberFeignClient;
    public WebController(NumberFeignClient numberFeignClient) {
        this.numberFeignClient = numberFeignClient;
    }
    @GetMapping("/hello")
    public String hello() {
        return numberFeignClient.test(new Random().nextInt(100));
    }
}
```

**Comment by LeoKotschenreuther** [comment] 2023-09-26 13:04
I have the same issue, the proposed workaround solved it for me as well.

**Comment by OlgaMaciaszek** [comment] 2023-12-04 18:00
Hello @johnnywiller, do you have a `micrometer-registry-{system}` dependency in your build setup (for example, `micrometer-registry-prometheus`)?

**Comment by spring-cloud-issues** [comment] 2023-12-11 18:04
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by johnnywiller** [comment] 2023-12-11 18:51
Sorry for the delay, so I tested with both including `micrometer-registry-prometheus` and without. Both yielded same result of not having feign metrics ootb.

**Comment by OlgaMaciaszek** [comment] 2023-12-12 14:17
Ok, @johnnywiller @LeoKotschenreuther please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue  - we'll look further into it then.

**Comment by spring-cloud-issues** [comment] 2023-12-19 14:19
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-12-26 14:19
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-12-26 14:19 UTC
Labels: waiting for feedback, feedback-reminder
