### ISSUE TITLE
feign.RetryableException: Incomplete output stream executing POST 

### ISSUE THREAD

**Issue by tangchen-blip** [spring-cloud/spring-cloud-openfeign#390] opened 2020-08-04 06:16 UTC
An error occurred when I overwrote the headers using RequestInterceptor.

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>2.1.2.RELEASE</version>
            <scope>compile</scope>
        </dependency>

```
RequestInterceptor.java
```
@Configuration
@Slf4j
public class FeignHeadConfiguration implements RequestInterceptor {

    @Override
    public void apply(RequestTemplate requestTemplate) {
        ServletRequestAttributes attrs = (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
        HttpServletRequest request = attrs.getRequest();
        Enumeration<String> headerNames = request.getHeaderNames();
        if (headerNames != null) {
            while (headerNames.hasMoreElements()) {
                String name = headerNames.nextElement();
                String value = request.getHeader(name);
                log.info("name:{},value:{}", name, value);
                requestTemplate.header(name, value);
            }
        }
    }
}
```

Exception

> feign.RetryableException: Incomplete output stream executing POST http://topic-provider/subjective/recitation/bringback/topic
> 	at feign.FeignException.errorExecuting(FeignException.java:132)
> 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:113)
> 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78)
> 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
> 	at com.sun.proxy.$Proxy155.bringBackTopic(Unknown Source)
> 	at com.jx.studyconsumer.consumer.StudyRecitationConsumer.bringBackTopic(StudyRecitationConsumer.java:650)
> 	at com.jx.studyconsumer.controller.StudyRecitationController.bringBackTopic(StudyRecitationController.java:389)
> 	at com.jx.studyconsumer.controller.StudyRecitationController$$FastClassBySpringCGLIB$$d41f988f.invoke(<generated>)
> 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
> 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
> 	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
> 	at com.jx.studyconsumer.controller.StudyRecitationController$$EnhancerBySpringCGLIB$$454c2167.bringBackTopic(<generated>)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
> 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
> 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.io.IOException: Incomplete output stream
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1523)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
> 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
> 	at feign.Client$Default.convertResponse(Client.java:143)
> 	at feign.Client$Default.execute(Client.java:68)
> 	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer$1.doWithRetry(RetryableFeignLoadBalancer.java:114)
> 	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer$1.doWithRetry(RetryableFeignLoadBalancer.java:94)
> 	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
> 	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
> 	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer.execute(RetryableFeignLoadBalancer.java:94)
> 	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer.execute(RetryableFeignLoadBalancer.java:54)
> 	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:104)
> 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
> 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
> 	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231)
> 	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
> 	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
> 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185)
> 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
> 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127)
> 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
> 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
> 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79)
> 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45)
> 	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
> 	at rx.Subscriber.setProducer(Subscriber.java:209)
> 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
> 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.Observable.subscribe(Observable.java:10423)
> 	at rx.Observable.subscribe(Observable.java:10390)
> 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
> 	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
> 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112)
> 	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:83)
> 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:108)
> 	... 82 common frames omitted
>

**Comment by g4ur4vs** [comment] 2020-09-01 07:10
Getting the same issue while doing an POST Request!

**Comment by g4ur4vs** [comment] 2020-09-01 07:12
Testing on spring-boot-starter-parent:2.2.2.RELEASE
<spring-cloud.version>Hoxton.RELEASE</spring-cloud.version>

**Comment by tangchen-blip** [comment] 2020-09-02 01:23
remove the header param content-length  can resolve it

**Comment by g4ur4vs** [comment] 2020-09-02 10:49
yes..resolved thanks!!

**Comment by OlgaMaciaszek** [comment] 2020-09-17 10:50
Closing as issue resolved.

**Closed by OlgaMaciaszek** 2020-09-17 10:50 UTC
Labels: waiting-for-triage

**Comment by mohdtabish999** [comment] 2021-06-16 11:06
headers.remove("content-length");
outputMessage = xyzClient.save(headers, message);

removing content-length resolved the issue

**Comment by scruel** [comment] 2021-11-02 05:29
> 
> 
> Closing as issue resolved.

Resolved? This issue caused by feign code...

**Comment by XWTiger** [comment] 2022-02-22 03:46
it

> remove the header param content-length can resolve it

it work

**Comment by parindia** [comment] 2025-07-25 15:03
headers.remove("content-length");
removing content-length resolved the issue.
