### ISSUE TITLE
Greenwich.RELEASE   --     Turn the plus sign“+” into space

### ISSUE THREAD

**Issue by Supermagic5** [spring-cloud/spring-cloud-openfeign#137] opened 2019-02-26 09:57 UTC
After upgrade Greenwich.RELEASE  ，feignclient  Turns the plus sign“+” into space

**Comment by ryanjbaxter** [comment] 2019-02-26 16:24
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by mdavydau** [comment] 2019-03-05 11:50
In my case it look like
Send via feign client  `Preprocess phone=[+123]`
Get on recipient `Cannot find by phone=[ 123]`

**Comment by ryanjbaxter** [comment] 2019-03-05 16:02
@mdavydau  https://github.com/spring-cloud/spring-cloud-openfeign/issues/137#issuecomment-467507591

**Comment by Supermagic5** [comment] 2019-03-06 06:24
> In my case it look like
> Send via feign client `Preprocess phone=[+123]`
> Get on recipient `Cannot find by phone=[ 123]`

Yes

**Comment by Supermagic5** [comment] 2019-03-06 06:31
Feign  Client Send  
@RequestMapping(value = "/api/user/user/getUserByUsernamePwd", method = RequestMethod.GET)
    public UserDTO getUserByUsernamePwd(
    		@RequestParam("username")String username,
    		@RequestParam("password")String password);
username ="aa"
password = “a+123456” [a+123456]

Feign Server  Receive  
username ="aa"
password = “a 123456”      [a 123456]

**Comment by mdavydau** [comment] 2019-03-06 11:00
@ryanjbaxter 
I made fork from https://github.com/spring-cloud-samples/feign-eureka and add example with "+".
Commit with current test: https://github.com/mdavydau/feign-eureka/commit/e64c8010ee781a0b45d39839b00724a9679093db
Code example: [feign-eureka.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/2935821/feign-eureka.zip)
Please send on your local env
`http://localhost:7211/phone` 
and check response from server with whitespace
`Hello World: 123 | HelloServer:10.168.0.183:7111`

**Comment by OlgaMaciaszek** [comment] 2019-03-21 11:59
@mdavydau @Supermagic5 I've tested this (using the sample @mdavydau has provided) against Spring Cloud Greenwich.RELEASE + Boot 2.1.3.RELEASE and it worked fine for me. If you want us to work on this, 
please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-issuemaster** [comment] 2019-03-28 12:00
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-04-04 11:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-04-04 11:59 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by Sroca3** [comment] 2019-07-05 14:55
There was a bug found in openfeign for this exact issue back in January, multiple actually.
https://github.com/OpenFeign/feign/issues/881
https://github.com/OpenFeign/feign/issues/879

**Comment by spencergibb** [comment] 2019-07-05 15:02
And the fix was https://github.com/OpenFeign/feign/pull/882

**Comment by Sroca3** [comment] 2019-07-05 15:05
Which, after doing some research, is available in 2.1.2-RELEASE of this library since feign was updated to 10.3.0 and the fix was present for 10.2.0. For spring cloud versions that would mean Greenwich.SR2
