### ISSUE TITLE
manually attached Feign requestInterceptors within Builder are being overridden by requestInterceptor beans

### ISSUE THREAD

**Issue by srikanth88infy** [spring-cloud/spring-cloud-openfeign#507] opened 2021-03-10 23:54 UTC
**Describe the bug**
We currently are creating a feign builder and explicitly adding requestInterceptor. 
` return Feign.builder()              
            .requestInterceptor(new CustomInterceptor()).logLevel(feignLoggerLevel());`

The above configuration used to work well until `spring-cloud-opefeign:2.2.5` .  We recently upgraded to `spring-cloud-openfeign-2.2.6` and we observed that our requestInteceptor was not being picked up. 

After debugging, we realized that `FeignClientFactory.java` will be overriding this value with @Bean RequestInterceptor found in the feign context. We did not have any RequestInterceptor beans created and hence, it updates the FeignBuilder with an empty interceptor.

Can I know if this is an intended change?  As we have multiple requestInterceptors for multiple clients, we prefer explicitly injecting it to the Builder.

**Comment by OlgaMaciaszek** [comment] 2021-03-16 13:45
Hello, @srikanth88infy, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue - it will be easier to verify the issue if we see the setup that was previously working and then has stopped.

**Comment by spring-cloud-issues** [comment] 2021-03-23 13:48
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-03-30 13:48
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-03-30 13:48 UTC
Labels: feedback-reminder, waiting for feedback
