### ISSUE TITLE
Incomplete output stream error

### ISSUE THREAD

**Issue by pgm-rookie** [spring-cloud/spring-cloud-openfeign#228] opened 2019-10-09 03:08 UTC
I updated spring-cloud-dependencies version to Greenwich.SR3, spring-boot-starter-parent version to 2.1.8.RELEASE.An exception occurred when service A(named saas-login) invoked service B(named saas-redis) through feign:

    c.n.loadbalancer.reactive.LoadBalancerCommand - Got error java.io.IOException: Incomplete output stream when executed on server DESKTOP-JJLLNU5:8084
    2019-10-09 10:52:16.211 [hystrix-saas-redis-79] DEBUG com.netflix.hystrix.AbstractCommand - Error executing HystrixCommand.run(). Proceeding to fallback logic ...
    feign.RetryableException: Incomplete output stream executing POST http://saas-redis/saas-redis/cache/batchGetCache
    ……
    Caused by: java.io.IOException: Incomplete output stream
    ……
I add a breakpoint on method of Service B and It was entered when Service A invoking this method in Service B, but Service A was not blocked and an exception has occurred, this may be due to asynchronous calls between services. But every thing was OK before I upgrading spring-cloud-dependencies version and spring-boot-starter-parent version.
  My feign client code is like below:

    @FeignClient(value = "saas-redis",fallback = SaasRedisAPIFallback.class)
    public interface SaasRedisAPI {

        @RequestMapping(value = "/saas-redis/cache/getCache", method = RequestMethod.POST )
        ResponseData<String> getCache(@RequestBody RequestData<CacheVO> requestData);

        @RequestMapping(value = "/saas-redis/cache/batchGetCache", method = RequestMethod.POST )
        ResponseData<Map<String,String>> batchGetCache(@RequestBody RequestData<List<CacheVO>> requestData);
    }

How to invoke other services synchronously as before and how to invoke other services asynchronously on the newest spring cloud dependency version, THKS!

**Comment by spencergibb** [comment] 2019-10-09 03:26
I'm afraid without a full stacktrace, we're not going to be much help.

**Comment by pgm-rookie** [comment] 2019-10-09 03:34
2019-10-09 11:30:15.817 [hystrix-saas-redis-120] DEBUG c.n.loadbalancer.reactive.LoadBalancerCommand - Got error java.io.IOException: Incomplete output stream when executed on server DESKTOP-JJLLNU5:8084
    2019-10-09 11:30:15.819 [hystrix-saas-redis-120] DEBUG com.netflix.hystrix.AbstractCommand - Error executing HystrixCommand.run(). Proceeding to fallback logic ...
    feign.RetryableException: Incomplete output stream executing POST http://saas-redis/saas-redis/cache/batchGetCache
	    at feign.FeignException.errorExecuting(FeignException.java:132)
	    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:113)
	    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78)
	    at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:109)
	    at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
	    at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
	    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	    at rx.Observable.unsafeSubscribe(Observable.java:10327)
	    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	    at rx.Observable.unsafeSubscribe(Observable.java:10327)
	    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	    at rx.Observable.unsafeSubscribe(Observable.java:10327)
	    at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	    at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	    at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	    at org.saas.businessCommon.config.FeignHystrixConcurrencyStrategy$WrappedCallable.call(FeignHystrixConcurrencyStrategy.java:116)
	    at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	    at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	    at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	    at java.util.concurrent.FutureTask.run(FutureTask.java)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	    at java.lang.Thread.run(Thread.java:748)
    Caused by: java.io.IOException: Incomplete output stream
	    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1523)
	    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	    at feign.Client$Default.convertResponse(Client.java:143)
	    at feign.Client$Default.execute(Client.java:68)
	    at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer$1.doWithRetry(RetryableFeignLoadBalancer.java:114)
	    at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer$1.doWithRetry(RetryableFeignLoadBalancer.java:94)
	    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
	    at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer.execute(RetryableFeignLoadBalancer.java:94)
	    at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer.execute(RetryableFeignLoadBalancer.java:54)
	    at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:104)
	    at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
	    at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
	    at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231)
	    at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
	    at rx.Observable.unsafeSubscribe(Observable.java:10327)
	    at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127)
	    at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	    at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	    at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79)
	    at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45)
	    at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
	    at rx.Subscriber.setProducer(Subscriber.java:209)
	    at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
	    at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	    at rx.Observable.unsafeSubscribe(Observable.java:10327)
	    at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
	    at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
	    at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185)
	    at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
	    at rx.Observable.unsafeSubscribe(Observable.java:10327)
	    at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	    at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	    at rx.Observable.unsafeSubscribe(Observable.java:10327)
	    at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127)
	    at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	    at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	    at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79)
	    at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45)
	    at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
	    at rx.Subscriber.setProducer(Subscriber.java:209)
	    at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
	    at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	    at rx.Observable.subscribe(Observable.java:10423)
	    at rx.Observable.subscribe(Observable.java:10390)
	    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	    at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	    at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112)
	    at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:83)
	    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:108)
	... 34 common frames omitted

**Comment by pgm-rookie** [comment] 2019-10-09 03:38
Service A start class:

    @EnableDiscoveryClient
    @SpringBootApplication(scanBasePackages = {"org.saas"},exclude = {DataSourceAutoConfiguration.class, DruidDataSourceAutoConfigure.class,MongoDataAutoConfiguration.class,MongoAutoConfiguration.class})
    @EnableFeignClients(basePackages = "org.saas")
    @EnableCircuitBreaker
    @EnableScheduling
    @MapperScan({"org.saas.login.dao","org.saas.login.dao2"})
    public class LoginApplication {

        public static void main(String[] args) {
            SpringApplication.run(LoginApplication.class, args);
        }
    }

Service B start class:

    @EnableDiscoveryClient
    @SpringBootApplication(exclude = {MongoAutoConfiguration.class, MongoDataAutoConfiguration.class})
    @EnableFeignClients(basePackages = "org.saas")
    @EnableCircuitBreaker
    @EnableScheduling
    @ComponentScan(basePackages = {"org.saas"},excludeFilters = @ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, classes = {MvcConfiguration.class}))
    public class SaasRedisApplication {

	    public static void main(String[] args) {
    		    SpringApplication.run(SaasRedisApplication.class, args);
	    }
    }

**Comment by debianwak** [comment] 2019-11-11 22:58
move pom.xml to another previous version for Spring cloud  from here: https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Greenwich-Release-Notes
like this: 
Greenwich.RELEASE

**Comment by ryanjbaxter** [comment] 2020-03-04 22:08
Can you try with Hoxton.SR2?  If you still experience the problem please provide a sample that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2020-03-11 22:12
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-03-18 22:09
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-03-18 22:09 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by bilal89hayat** [comment] 2024-03-04 09:34
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.1</version>
        <relativePath/>
    </parent>

<properties>
        <java.version>17</java.version>
        <spring-cloud.version>2023.0.0</spring-cloud.version>
</properties>

<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-feign</artifactId>
            <version>1.4.6.RELEASE</version>
 </dependency>

==========================
Solution :  updatedHttpHeaders.remove("content-length");

 ResponseEntity<Object> responseEntity = client.executeRequest(request, updatedHttpHeaders);

Note : Check ur spring and cloud compatibility.

**Comment by fantunao** [comment] 2024-08-01 12:20
> ```
> <parent>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-parent</artifactId>
>         <version>3.2.1</version>
>         <relativePath/>
>     </parent>
> ```
> 
> ```
> <properties>
>         <java.version>17</java.version>
>         <spring-cloud.version>2023.0.0</spring-cloud.version>
> </properties>
> 
> <dependency>
>             <groupId>org.springframework.cloud</groupId>
>             <artifactId>spring-cloud-starter-feign</artifactId>
>             <version>1.4.6.RELEASE</version>
>  </dependency>
> ```
> 
> ========================== Solution : updatedHttpHeaders.remove("content-length");
> 
> ResponseEntity responseEntity = client.executeRequest(request, updatedHttpHeaders);
> 
> Note : Check ur spring and cloud compatibility.

this work for me, thanks @bilal89hayat 
updatedHttpHeaders.remove("content-length");
