### ISSUE TITLE
[question] I can't get two maps in one request

### ISSUE THREAD

**Issue by matteoponzini** [spring-cloud/spring-cloud-openfeign#431] opened 2020-11-18 10:23 UTC
Hello everyone, this is the first time that I ask a question about a community maybe also give me advice on how to improve the questions.
I would like to try to send two different maps in one request as a param query, I have seen that there are various checks to not make it happen but they are two different types of maps
I put you as it should happen

**this is an example and not real code**

`String getAccounts(@RequestParam Map<String,List<Sting>> paramsExternalId, @RequestParam(value="-1") List<String> paramsEx, @RequestParam Map<String,String> paramsFilter`

because inside the map there could be these values --> paramsExternalId
                                                                                         key=345 value=[12442,13455] 
                                                                                         key=899 value=[3455,3425]
paramsFilter 
                      date= 1605694862
and the result of the url should be like this
url:/books?345=12442&345=12443&899=3455&date=1605694862

Because in the end what happens to me is that I have a map with n values ​​as a key in one case and I would like not to have a single map with a list or to use MultiKeyMap I would like to separate them

Thank you very much, if I have to ask the question about Stackoverflow it's not a problem but it seemed like a curious case to study

Thanks 
Matteo

**Comment by OlgaMaciaszek** [comment] 2021-01-21 11:47
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-01-28 11:52
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-02-04 11:52
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-02-04 11:52 UTC
Labels: feedback-reminder, waiting for feedback
