### ISSUE TITLE
‘max-retries-on-same-service-instance’ not working

### ISSUE THREAD

**Issue by AVP42** [spring-cloud/spring-cloud-openfeign#650] opened 2021-12-21 02:53 UTC
**Describe the bug**
Request doesn't retry on the same server when 'max-retries-on-same-service-instance' propertiy set to 2.

I did some debugging and I found that retry on the same server causes UnknowHostException.
It seems like retrievedServiceInstance is null when retry on the same server, which will not reconstruct the URI.
![image](https://user-images.githubusercontent.com/36760766/146861627-a364d33f-622d-4e40-a2c5-13ebdbae6b18.png)

![image](https://user-images.githubusercontent.com/36760766/146861789-17918da8-84e9-4f3f-8a94-5a967372fcdd.png)

ref:
spring-cloud release chain: 2020.0.4
spring-cloud-netflix-eureka + spring-cloud-openfeign + spring-cloud-loadbalancer

3ks!

**Comment by OlgaMaciaszek** [comment] 2021-12-23 10:48
@AVP42 thanks for reporting the issue. Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue, as a link to a GitHub repo with a small demo app and steps to reproduce in the README.

**Comment by spring-cloud-issues** [comment] 2022-02-04 01:06
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-02-04 01:06 UTC
Labels: waiting for feedback
