### ISSUE TITLE
spring-cloud-openfeign version 2.2.6 , requestInterceptor are not working, after adding in configuration Feign.Builder it is automatically getting removed.

### ISSUE THREAD

**Issue by Alok86JavaPro** [spring-cloud/spring-cloud-openfeign#434] opened 2020-11-29 05:07 UTC
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by Alok86JavaPro** [comment] 2020-11-29 05:45
@Bean(name = "feignBuilderGSS")
	@Scope("prototype")
	public Feign.Builder feignBuilderGSS() throws NoSuchAlgorithmException, KeyManagementException {
		Builder builder = Feign.builder();
//		if (!TenantServiceRunner.isLocal()) {
			LOGGER.debug("qualifier in feignBuilderGSS");
			if(LOGGER.isDebugEnabled())
				builder.logLevel(feign.Logger.Level.FULL);
			builder.client(feignClient());
//			builder.requestInterceptor(new FeignClientHeaderInterceptor());
			List<RequestInterceptor> interceptors = new ArrayList<>();
			interceptors.add(new FeignClientHeaderInterceptor());
			builder.requestInterceptors(interceptors);
			builder.build();
//		}
		return builder;
	}

**Comment by Alok86JavaPro** [comment] 2020-11-29 05:45
Above code what I am using to add requestIntwrceptor

**Comment by Alok86JavaPro** [comment] 2020-11-29 05:45
But that is not working

**Comment by ryanjbaxter** [comment] 2020-11-30 15:23
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2020-12-07 15:24
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-12-14 15:24
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-12-14 15:24 UTC
Labels: feedback-reminder, waiting for feedback
