### ISSUE TITLE
FeignClient contextId can not be resolved from config file

### ISSUE THREAD

**Issue by dongyinuo** [spring-cloud/spring-cloud-openfeign#781] opened 2022-11-04 03:12 UTC
### **this** is my code
<img width="641" alt="image" src="https://user-images.githubusercontent.com/45160106/199876287-25154cb3-a43a-4f6c-9699-66b909e76600.png">

in spring-cloud-starter-openfeign v2.2.1.RELEASE, it works good, when i upgrade the starter to v2.2.9.RELEASE. it can't work,
this is error:
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/45160106/199876198-8649ace7-9253-49a2-a771-9c420e8baff8.png">

when i diff v2.2.1.RELEASE and v2.2.9.RELEASE, i find the changes, 
![image](https://user-images.githubusercontent.com/45160106/199876505-6f927cd3-d8b8-484b-8ffc-aa6e1e496c3d.png)

and, the latest tag and main branch are the same

problem introduction
https://github.com/spring-cloud/spring-cloud-openfeign/pull/455
https://github.com/spring-cloud/spring-cloud-contract/issues/1303

need to fix ？

**Comment by SkyeBeFreeman** [comment] 2022-11-04 03:20
Notify https://github.com/Tencent/spring-cloud-tencent/issues/509

**Comment by OlgaMaciaszek** [comment] 2022-12-12 12:42
Hello @dongyinuo . None of these versions is supported. The only currently supported versions of SC OpenFeign are `3.1.5` and `4.0.x` (currently `RC3` available, `4.0.0` GA scheduled later this week). Please retry on a supported version. If the issue persists on a supported version, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2022-12-19 12:46
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-12-26 12:46
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-12-26 12:46 UTC
Labels: waiting for feedback, feedback-reminder
