### ISSUE TITLE
Caused by:Caused by: feign.FeignException$BadGateway: [502 Bad Gateway] feign.FeignException$BadGateway: [502 Bad Gateway]

### ISSUE THREAD

**Issue by MdcGIt** [spring-cloud/spring-cloud-openfeign#591] opened 2021-08-09 07:26 UTC
在nacos服务间调用时经常会出现

Caused by: feign.FeignException$BadGateway: [502 Bad Gateway]

**Comment by OlgaMaciaszek** [comment] 2021-09-08 17:07
Hello, @MdcGIt. This is an English language repo - please translate your comment to English if you would want us to take a look at it. Also, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-09-15 17:09
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-09-22 17:09
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-09-22 17:09 UTC
Labels: waiting for feedback, feedback-reminder

**Comment by JenSuper** [comment] 2022-03-15 06:50
> 你好，@MdcGIt 出现问题的问题，请问您是这样解决的吗？

一般502都是服务出现了问题，首先去排查一下注册中心的服务是否正常，节点之前是否正常通信

**Comment by en-hui** [comment] 2023-06-17 12:58
if (!this.name.startsWith("http")) {
                this.url = "http://" + this.name;
            } else {
                this.url = this.name;
            }
看到FeignClientFactoryBean类的getTarget()方法中，url取和name一样的值，我期望的是使用feign调用时，会讲服务名称通过注册中心解析为ip来访问，而不是通过配置host文件来映射服务名称和ip，请问有什么配置能达到我的期望吗

**Comment by Gretycos** [comment] 2023-09-03 16:47
> > 你好，@MdcGIt 出现问题的问题，请问您是这样解决的吗？
> 
> 一般502都是服务出现了问题，首先去排查一下注册中心的服务是否正常，节点之前是否正常通信

注册中心显示节点都健康，但是不知道为什么feign调用的时候就502，感觉是有一方被断开了连接但是另一方还连着，无解
