### ISSUE TITLE
Multiple @RequestPart (MultipartFile and DTO class) throws encoding error

### ISSUE THREAD

**Issue by wen-dell** [spring-cloud/spring-cloud-openfeign#752] opened 2022-09-14 14:44 UTC
Hi, below is my technology stack:

Spring Boot:  2.7.3
spring-cloud-starter-openfeign --> 3.1.4
feign-form-spring --> 3.8.0
feign-form --> 3.8.0
feign-core --> 10.12 

Here is my feign interface:

```
@PostMapping(value = "/v1/reservas-atuariais/upload")
Long upload(@RequestPart("dto") CreateReservaAtuarialDto dto, @RequestPart("file") MultipartFile file);
```

As you can see, I have one DTO class and a MultipartFile at the same time. Whenever I request this endpoint it gives this error: `error converting request body`.

I have tried many solutions and encoder implementations but none of them work. It seems like a bug I think. Can you guys give some help?

**Comment by OlgaMaciaszek** [comment] 2022-10-17 16:57
Hello @wen-dell , thanks for reporting the issue. It seems like this might be a duplicate of gh-201. Please try [this workaround](https://github.com/spring-cloud/spring-cloud-openfeign/issues/201#issuecomment-734368370) and let us know if it helps. If not, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue - this should be a link with a sample Feign Client app that reproduces the issue, along with the steps to reproduce, the expected result and the actual result.

**Comment by spring-cloud-issues** [comment] 2022-10-24 17:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-10-31 17:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-10-31 17:02 UTC
Labels: waiting for feedback, feedback-reminder
