### ISSUE TITLE
@SpringQueryMap serialVersionUID Duplicate key Exception. need help

### ISSUE THREAD

**Issue by RevisitMoon** [spring-cloud/spring-cloud-openfeign#746] opened 2022-09-06 17:28 UTC
**Describe the bug**
spring-cloud-openfeign-core-3.1.3.RELEASE

if super class define serialVersionUID and some class extends this super class and use `@SrpingQueryMap` to send request will throw "Duplicate key" Exception.

**Sample**
```
public class A implements Serializable {
      private static final long serialVersionUID = 1L;
}

public class B extends A implements Serializable {
      private static final long serialVersionUID = -4581321211925569500L;

      private String someKey;
}

public interface SomeFeignClient {
      String someFeignClientRquest(@SpringQueryMap B b);
}

@RestController
public class someController{
      @GetMapping("someUri")
      public String someFuntionName(B b){
          return someFeignClientRquest(b);
      }
}
```

how can i do fix this?

**Comment by RevisitMoon** [comment] 2022-09-06 17:41
This problem does not appear in spring-cloud-openfeign-core-2.2.6.RELEASE

**Comment by OlgaMaciaszek** [comment] 2022-10-17 16:54
Hello @RevisitMoon, thanks for submitting the issue. 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue -  this should be a link with a sample Feign Client app that reproduces the issue, along with the steps to reproduce, the expected result and the actual result.

**Comment by spring-cloud-issues** [comment] 2022-10-24 16:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-10-31 16:57
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-10-31 16:57 UTC
Labels: waiting for feedback, feedback-reminder
