### ISSUE TITLE
Spring cloud Feign client with zones

### ISSUE THREAD

**Issue by sandaAU** [spring-cloud/spring-cloud-openfeign#868] opened 2023-06-02 17:17 UTC
Here is info in Github: https://github.com/sandaAU/Macropods/blob/main/INFO.txt
 
**We have 3 subprojects:**
\SpringBoot-SpringCloud-projetcs_tutorialspoint.com_Olga-Sharma_1.6.23-23.35
\spring-cloud-eureka-client2	CLIENT 2
\spring-cloud-eureka-server2  	EUREKA SERVER
\spring-cloud-feign-client2	CLIENT 1
 
**At this file**
\spring-cloud-feign-client2\src\main\java\com\tutorialspoint\RestaurantController.java
is graph how clients 1 and 2 are called.
 
I tried to find some similar sample on Google, and nothing I found.
I check yours Github   , good samples 😊
 
I already tried other one project with Spring boot 2.0.5.RELEASE and Spring cloud Finchley.SR1 and this project is working well. I registered 3 zones: zone1, zone2, zone10, and everything is working with success. :-) But I’m not using at this project openfeign.

I tried find something about how openfeign can break Spring cloud with Zones.
When I found like turn off load balancer, did not work.

I spend with it couple days, include other working Eureka project with zones but without using openfeign.
I really tried everything to find problem.

If we choose Zone=USA == call PORT=8082 should be request sent only to client registered with zone name=USA. But is sent to client with zone name=EU as well.

Everything you can see in file INFO.txt.

I did not find any source on Github for this project, and owner of sample did not give me answer. :-( 

**Source sample is from:**
1) 
**Spring Cloud - Service Discovery Using Eureka**
https://www.tutorialspoint.com/spring_cloud/spring_cloud_service_discovery_using_eureka.htm
2) 
**Spring Cloud - Synchronous Communication with Feign**
https://www.tutorialspoint.com/spring_cloud/spring_cloud_synchronous_communication_with_feign.htm

**Comment by OlgaMaciaszek** [comment] 2023-12-04 17:45
Hello @sandaAU, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue, as a link to a GH repo with an executable app or tests and steps to reproduce. Please make sure you use supported versions. Spring Boot `2.7.18` or higher, Spring Cloud `2021.0.8` or higher.

**Comment by spring-cloud-issues** [comment] 2023-12-11 17:49
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-12-18 17:49
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-12-18 17:49 UTC
Labels: feedback-reminder
