### ISSUE TITLE
caused by: java.lang.IllegalStateException: PathVariable annotation was empty on param 0.

### ISSUE THREAD

**Issue by foxundermoon** [spring-cloud/spring-cloud-openfeign#178] opened 2019-04-22 15:25 UTC
unit test meet the exception

```log
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.yunpian.marketing.base.service.client.FlowServiceFeignClient': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: PathVariable annotation was empty on param 0.
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1645)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1178)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:258)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1325)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1291)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:584)
	... 55 more
Caused by: java.lang.IllegalStateException: PathVariable annotation was empty on param 0.
	at feign.Util.checkState(Util.java:126)
	at org.springframework.cloud.openfeign.annotation.PathVariableParameterProcessor.processArgument(PathVariableParameterProcessor.java:51)
	at org.springframework.cloud.openfeign.support.SpringMvcContract.processAnnotationsOnParameter(SpringMvcContract.java:238)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:108)
	at org.springframework.cloud.openfeign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:133)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:153)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:52)
	at feign.Feign$Builder.target(Feign.java:242)
	at org.springframework.cloud.openfeign.HystrixTargeter.target(HystrixTargeter.java:39)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:223)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:252)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:232)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:161)
	... 66 more

```

**Comment by spencergibb** [comment] 2019-04-22 18:01
Please post your client and versions

**Comment by foxundermoon** [comment] 2019-04-23 12:20
```
  @GetMapping("/flow/{id}")
  @ResponseBody
  Flow findByFlowId(@PathVariable String id);

```
after add default value ,test success. 
```
  @GetMapping("/flow/{id}")
  @ResponseBody
  Flow findByFlowId(@PathVariable("id") String id);

```

but the normal run is ok without default value `@RequestParam` and `@PathVariable`

**Comment by spencergibb** [comment] 2019-04-23 15:18
You have to enable parameter retention in the jdk `-parameters` or something

**Comment by foxundermoon** [comment] 2019-05-06 11:36
I use gradle to run test task .  how to pass the `-parameters` argument, and what the argument means.

**Comment by foxundermoon** [comment] 2019-05-06 11:37
why needent add the argument when   normal run  ？

**Comment by ryanjbaxter** [comment] 2019-06-19 19:38
I am not sure what you mean, the build has been passing fine for a while now on multiple CI systems.

**Comment by spring-issuemaster** [comment] 2019-06-26 19:43
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-07-03 19:43
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-07-03 19:43 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by leechor** [comment] 2020-03-30 13:05
I also meet exception, and spend some hours to solve it, finally the problem is maded by refactor Method class privateGetParameters(), the solvation is compiles use `javac -parameter ...", if you use idea, add "-parameters" under Java Compiler-> Additonal command line parameters settings. if you use gralde, and `    apply plugin: 'java'
    compileJava {
        options.compilerArgs << '-parameters'
    }`, note that clear your project before you try again

**Comment by boly38** [comment] 2022-01-14 13:55
equivalent for maven

```
               <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <compilerArgs>
                            <arg>-parameters</arg><!-- this fix java.lang.IllegalStateException: PathVariable annotation was empty on param 0. on feign clients-->
                        </compilerArgs>
```
