### ISSUE TITLE
nullpointexception

### ISSUE THREAD

**Issue by M1NGc** [spring-cloud/spring-cloud-openfeign#593] opened 2021-08-12 05:42 UTC
![image](https://user-images.githubusercontent.com/26264126/129144089-82eaa793-02af-4ca7-af8e-a6ad3f53e4e9.png)
feign-form 3.5

**Comment by OlgaMaciaszek** [comment] 2021-09-08 17:09
Hello, @M1NGc. Please describe the issue, including the steps to reproduce, the expected result and the actual result. Also, please 
provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-09-15 17:14
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-09-22 17:14
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-09-22 17:14 UTC
Labels: waiting for feedback, feedback-reminder
