### ISSUE TITLE
SpringEncoder sets UTF-8 charset encoding if used together with ResourceHttpMessageConverter

### ISSUE THREAD

**Issue by maverick1601** [spring-cloud/spring-cloud-openfeign#465] opened 2021-01-19 15:23 UTC
When using Spring together with Open-Feign to POST a binary Spring `org.springframework.core.io.Resource` the `SpringEncoder.encode()` does not honor the charset as being set to `null`. This is only done for `ByteArrayHttpMessageConverter` or `ProtobufHttpMessageConverter`.

**Comment by OlgaMaciaszek** [comment] 2021-01-21 14:02
Hello, @maverick1601. Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue. Please add a link to the sample repo.

**Comment by maverick1601** [comment] 2021-01-21 15:28
I have documented the behavior in the following test-case: https://github.com/maverick1601/encoder-sample/blob/master/src/test/kotlin/de/digitalfrontiers/spring/encoder/SpringEncoderTest.kt

The test uses two different upload mechanisms: byte array vs. spring resource. While byte array content is properly sent to the REST controller, the Spring resource is not. This is due to the SpringEncoder setting charset UTF-8 encoding and the Apache Http Client picking up this setting and interpreting the content as string. So, in fact, the problem with the SpringEncoder only affects certain HTTP-client. If you were to remove `feign-httpclient` dependency (favoring JDK HttpUrlConnection) the problem doesn't even show up, as the client implementation does not inspect the charset.

**Comment by Rob-HCL** [comment] 2021-01-21 21:19
If I'm not mistaken, this is the same bug as #357 .  If that's the case, then repro steps and the some proposed solutions can be found there as well.

**Comment by OlgaMaciaszek** [comment] 2021-01-26 09:12
Yes, @Rob-HCL, looks like a duplicate. Closing in favour of gh-357.

**Closed by OlgaMaciaszek** 2021-01-26 09:12 UTC
Labels: feedback-provided
