### ISSUE TITLE
header 中传 json 被分词搞的一团糟

### ISSUE THREAD

**Issue by FIshInInnkGIT** [spring-cloud/spring-cloud-openfeign#686] opened 2022-03-04 03:40 UTC
今天想在所有的请求头中加上一个统一的用户信息，采用了在header中传递json的方式。但结果令人意外，json被 feign.template.Template#parseTemplate 搞的一团糟。原因是进行了分词处理，但分词的标准是根据 “{}” 来进行的的，然后我想要写入的json就变成了另一个样子。
我知道在header中放入json不是一个好的选择，但是这个bug依然令人觉得十分糟糕。

···
source json： {"k1":"v1","k2":"v2"}
result: {"k1":"v1","k2"}
···

**Comment by FIshInInnkGIT** [comment] 2022-03-04 03:41
补充下版本信息 io.github.openfeign:feign-core:11.8

**Comment by OlgaMaciaszek** [comment] 2022-03-08 11:26
Hello, @FIshInInnkGIT this is an English language repo. We do not speak the language that the issue is reported in. If you would like us to look into the issue, please provide information in English.

**Comment by spring-cloud-issues** [comment] 2022-03-15 11:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-03-22 11:30
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-03-22 11:30 UTC
Labels: waiting for feedback, feedback-reminder
