### ISSUE TITLE
interceptors for a different client getting invoked when configure in application.yml

### ISSUE THREAD

**Issue by himnay** [spring-cloud/spring-cloud-openfeign#523] opened 2021-04-08 18:18 UTC
I have created multiple feign client and multiple interceptors. For the below settings, I could see during invoking client-a both RequestInterceptor1 and RequestInterceptor2 get to execute. I assume only the interceptor configured to the corresponding client should have executed.

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
      client-a:
        errorDecoder: com.org.decoderClientA
        requestInterceptors:
          - com.org.BasicAuthRequestInterceptor1
     client-b:
        errorDecoder: com.org.decoderClientB
        requestInterceptors:
          - com.org.BasicAuthRequestInterceptor2

**Comment by OlgaMaciaszek** [comment] 2021-04-16 10:06
Hello @himnay, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-04-23 10:07
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-04-30 10:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-04-30 10:07 UTC
Labels: feedback-reminder, waiting for feedback
