### ISSUE TITLE
 @SpringQueryMap doesn't support Map<String, String[]>

### ISSUE THREAD

**Issue by linianhui** [spring-cloud/spring-cloud-openfeign#256] opened 2019-12-05 03:11 UTC
**Describe the bug**
 @SpringQueryMap doesn't support Map<String, String[]>

**Sample**
```java
@FeignClient(name = "postman-echo", url = "https://postman-echo.com")
public interface PostmanEchoClient {
  @GetMapping(path = "/get")
  Object get(@SpringQueryMap Map<String, String[]> paramMap);
}
```

**Test**
```java
Map<String, String[]> paramMap = new HashMap<>(2);
paramMap.put("a", new String[] {"a1", "a2"});
paramMap.put("b", new String[] {"b1", "b2"});

postmanEchoClient.get(paramMap);
```

**Generated url**: `https://postman-echo.com/get?a=%5BLjava.lang.String%3B%405ed08faf&b=%5BLjava.lang.String%3B%4075386aa2`
**Expected  url**: `https://postman-echo.com/get?a=a1&a=a2&b=b1&b=b2`

**Comment by OLPMO** [comment] 2020-01-06 11:40
Has this bug been fixed?@spencergibb 
And cloud you provide a minimal demo to reproduce this  problem? @linianhui

**Comment by OlgaMaciaszek** [comment] 2020-01-09 15:20
We've not worked on that yet @OLPMO . Would you like to create a PR?

**Comment by xue8** [comment] 2020-01-10 14:44
A `key` corresponds to a `value`, so `Map <String, String []>` does not exist.

**Comment by Junhyunny** [comment] 2020-02-05 18:30
Hi, I find out this issue comes from the method which name is "addQueryMapQueryParameters" in ReflectiveFeign class . 

link - [https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/ReflectiveFeign.java](url)

The method only checks Iterable. I think some codeshould be added like
```
Object currValue = currEntry.getValue();
  if (currValue instanceof Iterable<?>) {
  	Iterator<?> iter = ((Iterable<?>) currValue).iterator();
  	while (iter.hasNext()) {
    Object nextObject = iter.next();
    values.add(nextObject == null ? null : encoded ? nextObject.toString() : UriUtils.encode(nextObject.toString()));
  	}
  } else if (currValue instanceof Object[]) {
  	for (Object nextObject : (Object[]) currValue) {
    values.add(nextObject == null ? null : encoded ? nextObject.toString() : UriUtils.encode(nextObject.toString()));
  	}
  } else {
  	values.add(currValue == null ? null : encoded ? currValue.toString() : UriUtils.encode(currValue.toString()));
  }
```

**Comment by spencergibb** [comment] 2020-02-05 19:26
@Junhyunny Then an issue should be opened here https://github.com/OpenFeign/feign/issues

**Comment by Junhyunny** [comment] 2020-02-09 10:21
@linianhui, here is my example. You can see the result what you want in log when you use List instead of array.

**link** - https://github.com/Junhyunny/openfeign-test
**test** - curl localhost:8080/testList

@spencergibb 
I found out other problem in my example. @RequestParam is {a=a1, b=b1}.
I expect @RequestParam {a=[a1, a2], b=[b1,b2]}.
What do you think of this? Is it bug?

**Comment by linianhui** [comment] 2020-02-09 12:33
@Junhyunny 

List can solve my current problem, Thank you for your help.

**Comment by Junhyunny** [comment] 2020-02-09 13:04
@spencergibb I found that result comes from "resolveArgument" method in RequestParamMap class. 

```
Map<String, String> result = new LinkedHashMap<>(parameterMap.size());
parameterMap.forEach((key, values) -> {
	if (values.length > 0) {
		result.put(key, values[0]);
	}
});
return result;
```

Resolver gets only first value in list. When I look over the code, I think they intentionally made resolver because they predicted values.

**Comment by spencergibb** [comment] 2020-03-02 15:25
Closing in favor of https://github.com/OpenFeign/feign/issues/1170

**Closed by spencergibb** 2020-03-02 15:25 UTC
Labels: bug
