### ISSUE TITLE
Feign Client ignoring Host Header

### ISSUE THREAD

**Issue by Viyaan** [spring-cloud/spring-cloud-openfeign#513] opened 2021-03-15 12:27 UTC
**Describe the bug**
I am trying to send a custom host header using feign client, but the consumer application is not picking what i send. 

Apart from Host, everyother header seems to be working as expected.

FeignClient:
@GetMapping(value = "${url}")
ResponseEntity<JSONObject> list(@PathVariable("name") String name,
            @RequestParam("id") String id, @RequestParam("modelName") String modelName,
            @RequestHeader(value = "Authorization", required = true) String authorizationHeader,
            @RequestHeader(value = "Host", required = true) String hostName);

After Enabling logs in caller application i can see feign is sending the host as intended

**Host: customheader.com**

But in my consumer app, the value of Host header is picked form DNS name ( Default behaviour).

**Comment by OlgaMaciaszek** [comment] 2021-04-12 12:13
Hello, @Viyaan, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-04-19 12:17
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-04-26 12:17
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-04-26 12:17 UTC
Labels: feedback-reminder, waiting for feedback
