### ISSUE TITLE
@RequestMapping(value = "") is not supported Nullpointer

### ISSUE THREAD

**Issue by florianmack** [spring-cloud/spring-cloud-openfeign#463] opened 2021-01-18 16:40 UTC
**Describe the bug**
My rest interface is automatically generated with basePath "/" this results in a @RequestMapping(value = "").
When my spring boot application starts the bean creation fails because of a nullpointer exception:

Caused by: java.lang.NullPointerException: null
	at org.springframework.cloud.openfeign.support.SpringMvcContract.processAnnotationOnClass(SpringMvcContract.java:179) ~[spring-cloud-openfeign-core-3.0.0.jar:3.0.0]

It seems that the processAnnotationOnClass function can not handle empty paths

**Comment by OlgaMaciaszek** [comment] 2021-01-19 11:38
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by florianmack** [comment] 2021-01-21 17:29
You just need a RestController with the annotation in the title and a feignClient of this restcontroller.
Wehn spring boot starts up the error will occure.
I'll provide an example when I have time but let me know if you can not reproduce it

**Comment by OlgaMaciaszek** [comment] 2021-01-26 09:10
Can your please provide that Rest Controller sample code?

**Comment by spring-cloud-issues** [comment] 2021-02-02 09:12
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-02-09 09:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-02-09 09:12 UTC
Labels: feedback-reminder, waiting for feedback
