### ISSUE TITLE
Feign RetryableException is not serialization

### ISSUE THREAD

**Issue by asharani-m** [spring-cloud/spring-cloud-openfeign#599] opened 2021-09-08 12:32 UTC
Unable to serialize the exception object RetryableException .

Get below exception :
"could not serialize :feign.Request"

Version : spring-cloud-openfeign : 3.0.3

Additional info:
While looking around for a solution , I came across this https://github.com/OpenFeign/feign/issues/1193.  So upgraded the feign-core to recent version 11.6 . 
After that above error("could not serialize :feign.Request") got resolved , but stuck up new exception 
"could not serialize :feign. TARGET$HardCodedTarget"

Any suggestions ? Workaround please?

**Comment by OlgaMaciaszek** [comment] 2021-09-08 18:00
Hello, @asharani-m. 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-09-15 18:04
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-09-22 18:04
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-09-22 18:04 UTC
Labels: waiting for feedback, feedback-reminder
