### ISSUE TITLE
Feign Client Configuration update does not seem to take effect

### ISSUE THREAD

**Issue by muvelus** [spring-cloud/spring-cloud-openfeign#349] opened 2020-05-18 17:11 UTC
**Describe the bug**
Though the timeout value has been changed to 120 secs, the Feign Client is unable to reflect the same when running the code. The Feign Client times out at 60 secs.
There are no application.properties file. (which if available may have overridden these values)

**Sample Code:**

     @Configuration
     public class FeignClientConfiguration {

    @Bean
    public ErrorDecoder getErrorDecoder() {
        return new CustomApiErrorDecoder();
    }

    @Bean
    public Request.Options requestOptions() {
        return new Request.Options(120000, 120000);
    }
}

**Feign Client:**

    @Component
    @RequestMapping("custom/copies")
    @FeignClient(name = "CustomCopyAPI", url = "${internal_api.custom}", configuration = 
    FeignClientConfiguration.class)
    public interface CustomCopyAdapterAPI {
    }

**Comment by OlgaMaciaszek** [comment] 2020-06-05 14:38
@muvelus Have just tested it against Spring Cloud `Hoxton.SR5` + Spring Boot `2.3.0.M4`, however, I was not able to reproduce the issue. 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-issuemaster** [comment] 2020-06-12 14:40
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-06-19 14:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-06-19 14:40 UTC
Labels: feedback-reminder, waiting for feedback
