### ISSUE TITLE
Openfeign passes subclass parameters, but the provider can only accept the parent class

### ISSUE THREAD

**Issue by tinet-dengsx** [spring-cloud/spring-cloud-openfeign#621] opened 2021-11-02 07:58 UTC
**Describe the bug**
consumer:
<img width="543" alt="1635837111346_5F2640CA-5AF2-4c67-B2FD-F5BA10C3736D" src="https://user-images.githubusercontent.com/80300791/139807677-fea1094e-0815-4182-b7d0-dddd16484a70.png">

provider:
<img width="543" alt="1635837111346_5F2640CA-5AF2-4c67-B2FD-F5BA10C3736D" src="https://user-images.githubusercontent.com/80300791/139807735-61816585-7be9-4651-b4d4-207c74a9dbf0.png">

**Comment by OlgaMaciaszek** [comment] 2021-11-09 12:17
Hello, @tinet-dengsx please provide a thorough issue description, including the steps to reproduce the issue, the expected result and the actual result. Also, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-11-16 12:20
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-11-23 12:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-11-23 12:20 UTC
