### ISSUE TITLE
The service invocation service data has changed

### ISSUE THREAD

**Issue by BlankCat-police** [spring-cloud/spring-cloud-openfeign#531] opened 2021-04-22 09:22 UTC
Version  openfeign 2.0.0.M1

The data format was List, and one of the data was "I.Zw.Twin point S". After calling other services, the data was changed to "I.Zw.Twin point S" and "". I was very sad and scolded by my boss, saying that there was something wrong with the code I wrote. Please help solve a 17-year-old developer from China. Thank you very much.

![image](https://user-images.githubusercontent.com/35520363/115690281-7b58cc80-a38f-11eb-9b2f-ca3d0b670288.png)

![image](https://user-images.githubusercontent.com/35520363/115690422-a04d3f80-a38f-11eb-9f0b-9015cc3ecc96.png)

**Comment by OlgaMaciaszek** [comment] 2021-05-07 10:41
Hello, @BlankCat-police, this is not enough information for us to verify the issue. Does not look like sth related to our implementation, however, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue if you want us to check it for you.

**Comment by spring-cloud-issues** [comment] 2021-05-14 10:45
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-05-21 10:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-05-21 10:42 UTC
Labels: feedback-reminder, waiting for feedback
