### ISSUE TITLE
Invalid one indexed parameters in openfeign

### ISSUE THREAD

**Issue by q2587218416** [spring-cloud/spring-cloud-openfeign#648] opened 2021-12-17 10:09 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/13169128/146527596-4e5709d1-3049-44b3-805b-c29628c4b8f3.png)

![image](https://user-images.githubusercontent.com/13169128/146527631-099ad81f-f3d9-424d-acdb-4710729feb80.png)

![image](https://user-images.githubusercontent.com/13169128/146527792-19460f11-4cae-47bd-bd1a-1dd4f31235db.png)
![image](https://user-images.githubusercontent.com/13169128/146527851-71683f88-06df-4b3b-ab2d-10d3471629be.png)

**Comment by OlgaMaciaszek** [comment] 2021-12-23 10:51
@q2587218416 Please provide a full description of the issue, including **steps to reproduce**, **expected outcome**, **actual outcome**. Also, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2022-02-04 01:06
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-02-04 01:06 UTC
Labels: waiting for feedback
