### ISSUE TITLE
For my openFeign implementation, noticing response decoding is taking too long

### ISSUE THREAD

**Issue by sumitsandal** [spring-cloud/spring-cloud-openfeign#969] opened 2024-01-23 03:36 UTC
In my project where I am using openFeign client for one of the big requests, noticed that it takes around 30 mins for decoding ( with open feign unbuild decoder , no customisation done). RPA void connect or read timeouts , increased the time. No doubt The response is big. 

ln logs of  API (being called from my feign client ), response was returned in seconds, but decoding entirely in my local took 30 mins.

I am thinking of enabling okHttp and enabling compression of responses. What else could be tried to figure out what’s the main issue ?

PS: For intellectual property reasons, can’t post code here

**Comment by OlgaMaciaszek** [comment] 2024-01-23 09:57
Hello @sumitsandal from what I see in your entry, it seems to me the component you're having trouble with is part of the OpenFeign/feign project and not Spring Cloud OpenFeign, so please report your issue there. If you don't think that's the case, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2024-01-30 09:58
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-02-06 09:58
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-02-06 09:58 UTC
Labels: waiting for feedback, feedback-reminder
