### ISSUE TITLE
Error calling through feign: BeanDefinitionStoreException

### ISSUE THREAD

**Issue by gkw666** [spring-cloud/spring-cloud-openfeign#975] opened 2024-01-31 07:54 UTC
```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.springframework.cloud.loadbalancer.annotation.LoadBalancerClientConfiguration]; nested exception is java.lang.IllegalArgumentException: Could not find class [org.springframework.boot.autoconfigure.condition.OnPropertyCondition]

  | at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189)
  | at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
  | at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
  | at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
  | at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
  | at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
  | at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
  | at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:155)
  | at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:108)
  | at org.springframework.cloud.context.named.NamedContextFactory.getInstances(NamedContextFactory.java:203)
  | at org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient.execute(FeignBlockingLoadBalancerClient.java:94)
  | at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119)
  | at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
  | at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
  | at org.springframework.cloud.openfeign.FeignCachingInvocationHandlerFactory$1.proceed(FeignCachingInvocationHandlerFactory.java:66)
  | at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:54)
  | at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:351)
  | at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
  | at org.springframework.cloud.openfeign.FeignCachingInvocationHandlerFactory.lambda$create$1(FeignCachingInvocationHandlerFactory.java:53)
  | at jdk.proxy3/jdk.proxy3.$Proxy213.queryCustomerGroupsList(Unknown Source)
  | at com.cn.service.openapi.application.service.impl.CustomerGroupJobServiceImpl.queryCustomerGroupInfo(CustomerGroupJobServiceImpl.java:86)
  | at com.cn.service.openapi.application.service.impl.CustomerGroupJobServiceImpl.insertCustomerGroup(CustomerGroupJobServiceImpl.java:42)
  | at com.cn.service.openapi.Interface.facade.dia.CustomerGroupJobController.lambda$insertCustomerGroup$0(CustomerGroupJobController.java:29)
  | at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  | at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
  | at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
  | at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
  | at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
  | at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
  | at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
  | Caused by: java.lang.IllegalArgumentException: Could not find class [org.springframework.boot.autoconfigure.condition.OnPropertyCondition]
  | at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:334)
  | at org.springframework.context.annotation.ConditionEvaluator.getCondition(ConditionEvaluator.java:124)
  | at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:96)
  | at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:226)
  | at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207)
  | at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175)
  | ... 29 more
  | Caused by: java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.condition.OnPropertyCondition
  | at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
  | at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
  | at java.base/java.lang.Class.forName0(Native Method)
  | at java.base/java.lang.Class.forName(Class.java:467)
  | at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
  | at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324)
  | ... 34 more

```

**Comment by OlgaMaciaszek** [comment] 2024-01-31 15:53
Hello @gkw666 , thanks for reporting the issue. 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). This looks like a duplicate of gh-475. Which versions of Spring Cloud OpenFeign and Spring Boot are you using?

**Comment by spring-cloud-issues** [comment] 2024-02-07 15:58
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-02-14 15:58
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-02-14 15:58 UTC
Labels: waiting for feedback, feedback-reminder
