### ISSUE TITLE
Feign client lazy initialization fails when using CompletableFuture.supplyAsync() to call the Feign client initially

### ISSUE THREAD

**Issue by maverick1601** [spring-cloud/spring-cloud-openfeign#475] opened 2021-01-28 12:42 UTC
**Describe the bug**
Feign client initialization is always lazy. As such, the first calling thread triggers the initialization, which may be another Spring component (e.g. REST controller) using `CompletableFuture.supplyAsync()` to do so. This uses `ForkJoinWorkerThread` underneath, resulting in a `ClassNotFoundException`, if and only if running in a dockerized environment based on Spring Boot Build Image plugin.

Using other JVM Executors(except `newWorkStealingExecutor)`, e.g. `fixedSizeThreadExecutor()`, does not result in this behavior. Also eagerly initializing the Feign client by calling it synchronously, e.g. from within a `CommandLineRunner`, circumvents this. Once, the Feign client is properly initialized, there is no problem, however, Feign does not yet support eager initialization.

**Sample**
A sample project with instructions to reproduce is provided here: https://github.com/maverick1601/openfeign-build-image-error

**Comment by OlgaMaciaszek** [comment] 2021-01-29 14:28
Example stacktrace:
```
 java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.condition.OnPropertyCondition
      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[na:na]
      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[na:na]
      at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
      at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
      at java.base/java.lang.Class.forName(Unknown Source) ~[na:na]
      at org.springframework.util.ClassUtils.forName(ClassUtils.java:284) ~[spring-core-5.3.3.jar:5.3.3]
      at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324) ~[spring-core-5.3.3.jar:5.3.3]
      at org.springframework.context.annotation.ConditionEvaluator.getCondition(ConditionEvaluator.java:124) ~[spring-context-5.3.3.jar:5.3.3]
      at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:96) ~[spring-context-5.3.3.jar:5.3.3]
      at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:88) ~[spring-context-5.3.3.jar:5.3.3]
      at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:71) ~[spring-context-5.3.3.jar:5.3.3]
       at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.doRegisterBean(AnnotatedBeanDefinitionReader.java:254) ~[spring-context-5.3.3.jar:5.3.3]
       at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:147) ~[spring-context-5.3.3.jar:5.3.3]
       at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.register(AnnotatedBeanDefinitionReader.java:137) ~[spring-context-5.3.3.jar:5.3.3]
      at org.springframework.context.annotation.AnnotationConfigApplicationContext.register(AnnotationConfigApplicationContext.java:168) ~[spring-context-5.3.3.jar:5.3.3]
      at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:122) ~[spring-cloud-context-3.0.1.jar:3.0.1]
      at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:101) ~[spring-cloud-context-3.0.1.jar:3.0.1]
       at org.springframework.cloud.context.named.NamedContextFactory.getInstances(NamedContextFactory.java:181) ~[spring-cloud-context-3.0.1.jar:3.0.1]
       at org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient.execute(FeignBlockingLoadBalancerClient.java:85) ~[spring-cloud-openfeign-core-3.0.1.jar:3.0.1]
      at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119) ~[feign-core-10.10.1.jar:na]
       at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-10.10.1.jar:na]
       at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-10.10.1.jar:na]
       at com.sun.proxy.$Proxy73.fetchIt(Unknown Source) ~[na:na]
       at de.digitalfrontiers.spring.build.image.SampleController$sampleApi$1.get(SampleController.kt:14) ~[classes/:na]
       at de.digitalfrontiers.spring.build.image.SampleController$sampleApi$1.get(SampleController.kt:9) ~[classes/:na]
      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[na:na]
       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[na:na]
       at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]
       at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]
       at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]
       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]
```

**Comment by OlgaMaciaszek** [comment] 2021-01-29 14:31
@maverick1601, thanks for reporting this. Will discuss it with the team and get back to you.

**Comment by OlgaMaciaszek** [comment] 2021-02-18 16:07
@maverick1601 we don't recommend using `CompletableFuture.supplyAsync()`, however, an enhancement that could be helpful here would be to offer an opt-in eager-loading mechanism. We don't think it's a priority at this point, so we would not work on this right now, however, we would welcome pull requests. As a reference, here is a PR, that introduced eager-loading in SC Ribbon where child contexts were being lazily initialised, very similarly to what we have in OpenFeign: https://github.com/spring-cloud/spring-cloud-netflix/commit/567a6c4a9f3a39ecfeb76d80f33c585c2ca1695a.

**Comment by DaviGia** [comment] 2021-10-04 16:20
Hi, is there any news about this issue and the associated PR? I encountered a similar issue when using openfeign client called within a method annotated as @Async that uses a ForkJoinPool executor. I currently had not found a solution.

**Comment by mgrigis** [comment] 2022-03-01 17:34
An alternative solution is to use rxjava,

mvn dep 

<dependency>
			<groupId>io.reactivex</groupId>
			<artifactId>rxjava</artifactId>
		</dependency>

**Comment by DenisKorolev** [comment] 2022-04-28 07:25
[The previous workaround](https://github.com/spring-cloud/spring-cloud-openfeign/issues/600#issuecomment-916737892) didn't work for me as constructor of LoadBalancerClientFactory without arguments is deprecated as a result that solution causes NPE.

Here is the modified version:
```java
    @Bean
    @ConditionalOnMissingBean
    public LoadBalancerClientFactory loadBalancerClientFactory(LoadBalancerClientsProperties properties) {
        return new LoadBalancerClientFactory(properties) {
            @Override
            protected AnnotationConfigApplicationContext createContext(String name) {
                // FIXME: temporary switch classloader to use the correct one when creating the context
                ClassLoader originalClassLoader = Thread.currentThread().getContextClassLoader();
                Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader());
                AnnotationConfigApplicationContext context = super.createContext(name);
                Thread.currentThread().setContextClassLoader(originalClassLoader);
                return context;
            }
        };
    }
```

**Comment by timosmit** [comment] 2022-05-10 06:28
> [The previous workaround](https://github.com/spring-cloud/spring-cloud-openfeign/issues/600#issuecomment-916737892) didn't work for me as the constructor of LoadBalancerClientFactory without arguments is deprecated, as a result that solution causes NPE.

@DenisKorolev is there any particular reason why you have omitted the following line from the previous workaround?
```java
clientFactory.setConfigurations(configurations.getIfAvailable(Collections::emptyList));
```

This line still appears in the `org.springframework.cloud.loadbalancer.config.LoadBalancerAutoConfiguration`.

**Comment by luoyi2019** [comment] 2022-06-17 02:23
I had the same problem

**Comment by lgbwonder** [comment] 2022-07-01 08:18
jdk11 had the problem, but jdk8 was ok.

**Comment by ashutosh049** [comment] 2022-08-30 12:28
I'm getting this `OnBeanCondition` error. Seems quite similar.
As soon as my `CompletableFuture<Optional<Object>>` starts to execute, it fails with below logs. I can't figure out what's the issue here. On local dev machine it's running good, fails on ec2 linux.

```shell
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at com.myapp.cricket.app.Application.main(Application.java:40) ~[classes!/:1.0.0-SNAPSHOT.1]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:1.0.0-SNAPSHOT.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[app.jar:1.0.0-SNAPSHOT.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:1.0.0-SNAPSHOT.1]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:1.0.0-SNAPSHOT.1]
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Could not find class [org.springframework.boot.autoconfigure.condition.OnBeanCondition]
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[na:na]
        at com.myapp.cricket.app.bootstrap.SpmConfigLookupRunner.run(SpmConfigLookupRunner.java:72) ~[classes!/:1.0.0-SNAPSHOT.1]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        ... 11 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not find class [org.springframework.boot.autoconfigure.condition.OnBeanCondition]
        at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:334) ~[spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.annotation.ConditionEvaluator.getCondition(ConditionEvaluator.java:124) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:96) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:88) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:71) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.doRegisterBean(AnnotatedBeanDefinitionReader.java:254) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:147) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.register(AnnotatedBeanDefinitionReader.java:137) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.annotation.AnnotationConfigApplicationContext.register(AnnotationConfigApplicationContext.java:162) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:120) ~[spring-cloud-context-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:102) ~[spring-cloud-context-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.cloud.context.named.NamedContextFactory.getInstance(NamedContextFactory.java:146) ~[spring-cloud-context-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.cloud.loadbalancer.support.LoadBalancerClientFactory.getInstance(LoadBalancerClientFactory.java:60) ~[spring-cloud-loadbalancer-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.choose(BlockingLoadBalancerClient.java:81) ~[spring-cloud-loadbalancer-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.cloud.client.loadbalancer.InterceptorRetryPolicy.canRetry(InterceptorRetryPolicy.java:59) ~[spring-cloud-commons-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.retry.support.RetryTemplate.canRetry(RetryTemplate.java:375) ~[spring-retry-1.2.5.RELEASE.jar!/:na]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:278) ~[spring-retry-1.2.5.RELEASE.jar!/:na]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180) ~[spring-retry-1.2.5.RELEASE.jar!/:na]
        at org.springframework.cloud.client.loadbalancer.RetryLoadBalancerInterceptor.intercept(RetryLoadBalancerInterceptor.java:77) ~[spring-cloud-commons-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:77) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:739) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:612) ~[spring-web-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at com.myapp.cricket.app.web.exchange.ExchangeService.exchange(ExchangeService.java:85) ~[classes!/:1.0.0-SNAPSHOT.1]
        at com.myapp.cricket.app.web.exchange.ExchangeService$$FastClassBySpringCGLIB$$df1cc642.invoke(<generated>) ~[classes!/:1.0.0-SNAPSHOT.1]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at com.myapp.cricket.app.web.exchange.ExchangeService$$EnhancerBySpringCGLIB$$eba28ab1.exchange(<generated>) ~[classes!/:1.0.0-SNAPSHOT.1]
        at com.myapp.cricket.app.service.SpmContinentAndCountryConfigLookupService.getContinentAndCountryByContinentId(SpmContinentAndCountryConfigLookupService.java:157) ~[classes!/:1.0.0-SNAPSHOT.1]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
        at com.myapp.cricket.app.service.SpmContinentAndCountryConfigLookupService.spmContinentAndCountryFetchUpdate(SpmContinentAndCountryConfigLookupService.java:125) ~[classes!/:1.0.0-SNAPSHOT.1]
        at com.myapp.cricket.app.service.SpmContinentAndCountryConfigLookupService.spmContinentAndCountryFetchUpdate(SpmContinentAndCountryConfigLookupService.java:67) ~[classes!/:1.0.0-SNAPSHOT.1]
        at com.myapp.cricket.app.bootstrap.SpmConfigLookupRunner.lambda$fetchSpmContinentsAndCountriesFuture$0(SpmConfigLookupRunner.java:84) ~[classes!/:1.0.0-SNAPSHOT.1]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.condition.OnBeanCondition
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
        at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
        at java.base/java.lang.Class.forName(Class.java:468) ~[na:na]
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:284) ~[spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324) ~[spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        ... 43 common frames omitted

```

**Comment by DDAaTao** [comment] 2022-09-02 02:34
My problem like it,  [#1139](https://github.com/spring-cloud/spring-cloud-commons/issues/1139)

**Comment by HJK181** [comment] 2022-10-05 06:10
I'm facing the exact same problem after an update from Spring 2.3 to Spring 2.7 + Java update from 14 to 17.
We are not using any @Async or CompletableFuture, but the feign client is called by an Grizzly Thread that is outside part of our core infrastructure and needs to call another running Spring Boot app via Feign. This used to work without any problems before the update. Disappointed way too often to see such an issue open for such a long time with no prospect of a solution

**Comment by Psimage** [comment] 2022-10-30 00:02
Made [another sample project](https://github.com/Psimage/spring-class-not-found) that reproduces a problem. It also contains a submodule with [proposed workaround](https://github.com/spring-cloud/spring-cloud-openfeign/issues/475#issuecomment-1111842074) by @DenisKorolev. It also includes a test with boot 2.3 and ribbon that works fine. And a sample for when eager-loading enabled for Spring's loadbalancer (available in boot 3+, but you can implement the same logic for yourself if it fits).

**Comment by ruanun** [comment] 2022-10-31 09:02
Hi. In what version was the "openfeign asynchronous call error "problem fixed?

**Comment by OlgaMaciaszek** [comment] 2022-10-31 11:13
This issue is still open.

**Comment by SuperChrisliu** [comment] 2022-12-01 06:08
> Made [another sample project](https://github.com/Psimage/spring-class-not-found) that reproduces a problem. It also contains a submodule with [proposed workaround](https://github.com/spring-cloud/spring-cloud-openfeign/issues/475#issuecomment-1111842074) by @DenisKorolev. There are also a test with boot 2.3 and ribbon that works fine and a test for when eager-loading enabled for Spring's loadbalancer (available in boot 3+, but you can implement the same logic for yourself if it fits).

use maven package to jar file then run jar , it get ClassNotFoundException 

not package jar file while not get ClassNotFoundException

**Comment by poolsnowhui** [comment] 2023-02-07 06:19
linux in docker had the problem in jdk17, but windows was ok in jdk17.

**Comment by kisick** [comment] 2023-04-15 10:48
> > [The previous workaround](https://github.com/spring-cloud/spring-cloud-openfeign/issues/600#issuecomment-916737892) didn't work for me as the constructor of LoadBalancerClientFactory without arguments is deprecated, as a result that solution causes NPE.
> 
> @DenisKorolev is there any particular reason why you have omitted the following line from the previous workaround?
> 
> ```java
> clientFactory.setConfigurations(configurations.getIfAvailable(Collections::emptyList));
> ```
> 
> This line still appears in the `org.springframework.cloud.loadbalancer.config.LoadBalancerAutoConfiguration`.


If you have a custom loadbalancer configure, like 
`@LoadBalancerClients(defaultConfiguration = CustomLoadBalancerConfiguration.class)`
you should add it
`loadBalancerClientFactory.setConfigurations(configurations.getIfAvailable(Collections::emptyList));`
```
    @Bean
    @ConditionalOnMissingBean
    public LoadBalancerClientFactory loadBalancerClientFactory(LoadBalancerClientsProperties properties, ObjectProvider<List<LoadBalancerClientSpecification>> configurations) {
        LoadBalancerClientFactory loadBalancerClientFactory = new LoadBalancerClientFactory(properties) {
            @Override
            protected AnnotationConfigApplicationContext createContext(String name) {
                // FIXME: temporary switch classloader to use the correct one when creating the context
                ClassLoader originalClassLoader = Thread.currentThread().getContextClassLoader();
                Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader());
                AnnotationConfigApplicationContext context = super.createContext(name);
                Thread.currentThread().setContextClassLoader(originalClassLoader);
                return context;
            }
        };
        loadBalancerClientFactory.setConfigurations(configurations.getIfAvailable(Collections::emptyList));
        return loadBalancerClientFactory;
    }
```

**Comment by HJK181** [comment] 2023-04-17 05:44
We experience the same issue with k8ss resource limits. After we removed the CPU limit of 1, our application failed to execute Feign requests.

**Comment by BADRKAC** [comment] 2023-06-26 11:31
Spring boot  3.1.0
spring-cloud 2022.0.3
Java 17

The previous workaround is working with little changes

```
 @Bean
  @ConditionalOnMissingBean
  public LoadBalancerClientFactory loadBalancerClientFactory(LoadBalancerClientsProperties properties) {
    return new LoadBalancerClientFactory(properties) {
      @Override public AnnotationConfigApplicationContext createContext(String name) {
        ClassLoader originalClassLoader = Thread.currentThread().getContextClassLoader();
        Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader());
        AnnotationConfigApplicationContext context = (AnnotationConfigApplicationContext) super.createContext(name);
        Thread.currentThread().setContextClassLoader(originalClassLoader);
        return context;
      }
    };
  }
```

**Comment by crmky** [comment] 2023-07-07 06:15
We got similar issue in one of our applications. After investigation, we found this is caused by https://bugs.openjdk.org/browse/JDK-8172726.

Start with Java 9, `ForkJoinPool` creates thread using system context loader, refer to https://github.com/openjdk/jdk11u/blob/master/src/java.base/share/classes/java/util/concurrent/ForkJoinPool.java#L721.

If we run applications in IDE, the system context loader has been used to load Spring and application classes, so it's not easy to reproduce this issue. If we run applications from command line using fat JAR, `org.springframework.boot.loader.LaunchedURLClassLoader` will be used to load those classes instead. If threads switch to use system context loader, it will not be able to load Spring and other classes inside the fat JAR.

**Comment by crmky** [comment] 2023-07-07 08:55
The fix in https://github.com/spring-cloud/spring-cloud-commons/pull/1098 tries to use the class loader of parent `ApplicationContext` in child `ApplicationContext`:
> context = new AnnotationConfigApplicationContext(beanFactory);
> context.setClassLoader(this.parent.getClassLoader());

However typically the parent `ApplicationContext` doesn't set class loader explicitly, it will use `ClassUtils.getDefaultClassLoader()` to return the default class loader. Unfortunately that implementation will return context class loader if that has been set.

**Comment by crmky** [comment] 2023-07-07 23:52
Our applications use a different workaround. We created `ApplicationContextInitializer` implementation (and added to `spring.factories`) to manually set the class loader as the context class loader who starts the application. 

```
public class ClassLoaderApplicationContextInitializer
        implements ApplicationContextInitializer<ConfigurableApplicationContext> {

    @Override
    public void initialize(ConfigurableApplicationContext applicationContext) {
        applicationContext.setClassLoader(applicationContext.getClassLoader());
    }
}
```

**Comment by OlgaMaciaszek** [comment] 2023-07-19 17:22
Thanks for looking into it @crmky. Have submitted a PR to address this in Commons.

**Comment by OlgaMaciaszek** [comment] 2023-07-20 08:43
Fixed with https://github.com/spring-cloud/spring-cloud-commons/pull/1256.

**Closed by OlgaMaciaszek** 2023-07-20 08:43 UTC
Labels: enhancement
