### ISSUE TITLE
java.lang.NoSuchMethodError: feign.SynchronousMethodHandler$Factory.<init>

### ISSUE THREAD

**Issue by tongzige** [spring-cloud/spring-cloud-openfeign#727] opened 2022-07-21 08:04 UTC
![image](https://user-images.githubusercontent.com/40231684/180162164-7a5b6f55-fedd-43da-89f8-081602701ec4.png)

Unexpected exception during bean creation; nested exception is java.lang.NoSuchMethodError: feign.SynchronousMethodHandler$Factory.<init>(Lfeign/Client;Lfeign/Retryer;Ljava/util/List;Lfeign/Logger;Lfeign/Logger$Level;ZZLfeign/ExceptionPropagationPolicy;Z)V

spring-cloud-openfeign-3.1.3

**Comment by OlgaMaciaszek** [comment] 2022-09-05 14:01
Hello, @tongzige please provide a description of the issue, including steps to reproduce, the expected result and the actual result. Also, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2022-09-12 14:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-09-19 14:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-09-19 14:02 UTC
Labels: waiting for feedback, feedback-reminder
