### ISSUE TITLE
FeignClient annotation does not recognize yaml properties

### ISSUE THREAD

**Issue by sergiopacezup** [spring-cloud/spring-cloud-openfeign#176] opened 2019-04-15 15:26 UTC
Given that my client is annotated with:
```
@FeignClient(url = "${myapp.service.url}/api/", name = "serviceClient" configuration = [ServiceConfiguration::class])
```
If using an "application.properties" everything works as expected.
If using an "application.yaml" like:
```
myapp:
  service:
    url: http://example.com
```
Results in 
```
java.lang.IllegalArgumentException: Could not resolve placeholder 'myapp.service.url' in value "http://${myapp.service.url}/api/"
```
OTOH, if I change my properties.yaml to:
```
myapp.service.url: http://example.com
```
Everything works as expected again. The (working) second form is unsual when using yaml and AFAIK they should be equivalent.

Regards

**Comment by ryanjbaxter** [comment] 2019-04-25 14:31
Shouldn't is be `${myapp.service.url}/api/`?

**Comment by sergiopacezup** [comment] 2019-04-25 16:13
Sorry, it was o typo on the issue, updated it.

**Comment by ryanjbaxter** [comment] 2019-05-01 20:40
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-05-15 20:43
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-05-15 20:43 UTC
Labels: feedback-reminder, waiting for feedback
