### ISSUE TITLE
Springboot 2.1.1 with Eureka and Cloud Config with Open feign

### ISSUE THREAD

**Issue by tanuja3088** [spring-cloud/spring-cloud-openfeign#112] opened 2019-01-24 14:14 UTC
I am trying to use Feign Client with Eureka, and as of now the call isn't going to my request service
Spring cloud version Greenwich.RC1
````
@FeignClient(name = "DATA-MODELER")
public interface FeignClientServiceForDM {

    @RequestMapping(method = RequestMethod.POST, value="/rest/modelData/", consumes = "application/json")
       //ToDo: Remove this method. For Testing only
    @GetMapping(value="/rest/modelData/coupon/all")
    public String getCoupons();
}
````

My application class
```
@SpringBootApplication
@EnableDiscoveryClient
@EnableFeignClients
public class DataDriverApplication {
    public static void main(@NotNull final String[] args) throws Exception {
        SpringApplication.run(DriverApplication.class, args);
    }

```
The url client forms is http://DATA-MODELER it works fine if the add the url parameter to feign client but when I try it with eureka it fails

my bootstrap.properties file
````
spring.application.name=data-modeler
eureka.client.service-url.default-zone=http://localhost:8761/eureka
spring.cloud.config.uri=http://localhost:8888
spring.profiles.active=dev
management.endpoints.web.exposure.include=refresh
eureka.instance.preferIpAddress=true

==logs===
``.2019-01-25 14:16:52.918  INFO 13844 --- [onPool-worker-3] c.s.ldp.services.ModelerService      : Fetcher being called
-.-.-.2019-01-25 14:17:03.128  INFO 13844 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_DATA-DRIVER/RD0053121.global.scd.scania.com:data-driver - Re-registering apps/DATA-DRIVER
2019-01-25 14:17:03.128  INFO 13844 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_DATA-DRIVER/RD0053121.global.scd.scania.com:data-driver: registering service...
2019-01-25 14:17:03.303  INFO 13844 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_DATA-DRIVER/RD0053121.global.scd.scania.com:data-driver - registration status: 204
-.-.-.-.-.-.-.-.-.-.2019-01-25 14:17:33.081  WARN 13844 --- [scoveryClient-0] c.netflix.discovery.TimedSupervisorTask  : task supervisor timed out

java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205) [na:1.8.0_171]
	at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:66) ~[eureka-client-1.9.8.jar:1.9.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]``

**Comment by spencergibb** [comment] 2019-01-28 17:07
What is the error when you use eureka? That exception is asynchronous and not the error you would get making the feign call.

**Comment by tanuja3088** [comment] 2019-01-29 12:04
also have this warning message in my log

`2019-01-29 12:53:53.590  WARN 512 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.`

**Comment by ryanjbaxter** [comment] 2019-02-01 21:03
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-02-08 21:04
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-15 21:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-15 21:07 UTC
Labels: feedback-reminder, waiting for feedback
