### ISSUE TITLE
can't support SpringQueryMap and pageable feature

### ISSUE THREAD

**Issue by optimistic9527** [spring-cloud/spring-cloud-openfeign#175] opened 2019-04-12 10:13 UTC
hi ! about use SpringQueryMap and pageable

my version:

spring-cloud-open-feign 2.1.0 RELEASE
feign-core: 10.0.0

my code:
```
@FeignClient(name = ModuleConst.USER_MODULE_SERVICE_ID, fallback = MerchantClientFallback.class)
public interface MerchantFeignClient {
    /**
     * common api prefix
     */
    String API_PATH = "/merchant";

    @RequestMapping(value = API_PATH + "/{merchantId}", method = RequestMethod.GET)
    ResultVO<MerchantInfoVO> acquireMerchantInfo(@PathVariable("merchantId") Long merchantId);

    @RequestMapping(value = API_PATH + "/updateMerchant", method = RequestMethod.POST)
    ResultVO updateUser(@RequestBody MerchantInfo merchantInfo);

    @RequestMapping(value = API_PATH + "/test", method = RequestMethod.GET)
    ResultVO test(@SpringQueryMap MerchantInfo merchantInfo,Pageable pageable);
}
```

```
   @GetMapping("/test")
    public ResultVO test(MerchantInfo merchantInfo, Pageable pageable) {
        ResultVO test = merchantFeignClient.test(merchantInfo,pageable);
        return test;
    }
```
```
 @GetMapping("/test")
    public ResultVO test(MerchantInfo merchantInfo,@PageableDefault Pageable pageable) {
        System.out.println(merchantInfo);
        System.out.println(pageable);
        return ResultVO.success();
    }
```
result:
get not support HttpRequestMethodNotSupportedException

**Comment by ryanjbaxter** [comment] 2019-04-15 21:21
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-04-24 12:20
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by noone6931** [comment] 2019-04-26 07:13
how to use pageable in feign??

**Comment by spring-issuemaster** [comment] 2019-05-15 20:44
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-05-15 20:44 UTC
Labels: feedback-reminder, waiting for feedback
