### ISSUE TITLE
Error creating bean with name 'requestMappingHandlerMapping' 

### ISSUE THREAD

**Issue by SoftwareKing** [spring-cloud/spring-cloud-openfeign#14] opened 2018-04-01 08:54 UTC
Finchley.M9-> spring-cloud-openfeign
```yml
feign:
    compression:
        request:
            enabled: true
            mime-types: text/xml,application/xml,application/json # 配置压缩支持的MIME TYPE
            min-request-size: 2048  # 配置压缩数据大小的下限
        response:
            enabled: true # 配置响应GZIP压缩
```

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1710) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at cn.springcloud.book.feign.SpringCloudFeignApplication.main(SpringCloudFeignApplication.java:13) [classes/:na]
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724) ~[na:1.8.0_112]
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531) ~[na:1.8.0_112]
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[na:1.8.0_112]
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[na:1.8.0_112]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[na:1.8.0_112]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[na:1.8.0_112]
	at java.lang.Class.createAnnotationData(Class.java:3521) ~[na:1.8.0_112]
	at java.lang.Class.annotationData(Class.java:3510) ~[na:1.8.0_112]
	at java.lang.Class.createAnnotationData(Class.java:3526) ~[na:1.8.0_112]
	at java.lang.Class.annotationData(Class.java:3510) ~[na:1.8.0_112]
	at java.lang.Class.getAnnotation(Class.java:3415) ~[na:1.8.0_112]
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258) ~[na:1.8.0_112]
	at java.lang.Class.isAnnotationPresent(Class.java:3425) ~[na:1.8.0_112]
	at org.springframework.core.annotation.AnnotatedElementUtils.hasAnnotation(AnnotatedElementUtils.java:575) ~[spring-core-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.isHandler(RequestMappingHandlerMapping.java:177) ~[spring-webmvc-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:217) ~[spring-webmvc-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:188) ~[spring-webmvc-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:129) ~[spring-webmvc-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	... 16 common frames omitted

```

```xml
<properties>
        <spring-cloud.version>Finchley.M9</spring-cloud.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
        <pluginRepository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by ryanjbaxter** [comment] 2018-04-02 10:51
Can you please place all the code to reproduce this in a git repo or attach it to the issue as a zip so we can reproduce this?

**Comment by SoftwareKing** [comment] 2018-04-03 16:11
@ryanjbaxter 
[ch2-1.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/1872367/ch2-1.zip)

**Comment by SoftwareKing** [comment] 2018-04-03 16:13
@ryanjbaxter I attach ch2-1
![image](https://user-images.githubusercontent.com/6858857/38261490-ebc15da0-379c-11e8-8831-8c9b794a1903.png)

**Comment by SoftwareKing** [comment] 2018-04-08 03:10
@ryanjbaxter  I attach ch2-1

**Comment by niuchang3** [comment] 2018-04-13 05:32
@SoftwareKing 
Is the problem solved?
I have this problem here, too.

**Comment by gl81567405** [comment] 2018-04-13 05:49
Is the problem solved?
I have this problem here, too. application.

**Comment by niuchang3** [comment] 2018-04-13 05:57
[microserver-test.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/1905964/microserver-test.zip)
@ryanjbaxter   Can you see it for me?

**Comment by SoftwareKing** [comment] 2018-04-13 09:28
@niuchang3 目前没有，最近太忙了。

**Comment by chen497147884** [comment] 2018-04-13 10:04
@niuchang3 你的zip代码里面有个maven是你自己下不来。microserver-user-api

**Comment by SoftwareKing** [comment] 2018-04-13 10:06
@chen497147884 你看我的例子，拉下来调整一下。

**Comment by chen497147884** [comment] 2018-04-13 10:09
@SoftwareKing 你的例子 我看了 无法注入HelloFeignService 不知道是官方BUG还是我们配置的不对

**Comment by niuchang3** [comment] 2018-04-13 10:10
@chen497147884  在pom 文件增加`
	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/libs-milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>`

**Comment by SoftwareKing** [comment] 2018-04-13 10:11
@chen497147884 你加我qq吧2508203324，去掉压缩配置信息，是可以run的

**Comment by chen497147884** [comment] 2018-04-13 11:05
@niuchang3 pom中加https://repo.spring.io/libs-milestone何用？我说的是你的自己的jar com.carl.microserver.app.microserver-user-api  是你自己的 不在公网上

**Comment by chen497147884** [comment] 2018-04-13 11:07
@niuchang3 
`<dependency>
			<groupId>com.carl.microserver.app</groupId>
			<artifactId>microserver-user-api</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>`

这个jar包 是你自己私有的 你应该把它也打到zip文件中。不然别人根本无法编译的工程

**Comment by SoftwareKing** [comment] 2018-04-22 08:28
@ryanjbaxter @spencergibb  github code:https://github.com/SoftwareKing/ch2-1.git

**Comment by SoftwareKing** [comment] 2018-04-23 16:09
@ryanjbaxter @spencergibb github code:https://github.com/SoftwareKing/ch2-1.git

**Comment by ryanjbaxter** [comment] 2018-04-23 20:53
Remove the version from `spring-boot-starter-web`
https://github.com/SoftwareKing/ch2-1/blob/master/pom.xml#L35

**Comment by ryanjbaxter** [comment] 2018-04-25 23:27
Thanks @xjune123 I see the problem now.  I think this is also related to https://github.com/spring-cloud/spring-cloud-netflix/issues/2797 if you are using the Edgware release train.

**Comment by ryanjbaxter** [comment] 2018-05-10 18:53
Fixed in 9ac36c7f3f2fe4358429f682f06ae338ff7a5380

**Closed by ryanjbaxter** 2018-05-10 18:53 UTC

**Comment by SoftwareKing** [comment] 2018-06-29 08:40
@cybfly 你的问题不是使用Feign开启压缩引起的，问题放错地方了

**Comment by cybfly** [comment] 2018-06-29 09:21
@SoftwareKing Ok,  because i see the same requestMappingHandlerMapping...and i will ask in spring-boot project,

**Comment by qianglu1989** [comment] 2018-07-12 13:01
配置 feign.compression.response.enabled=false 即可解决这个问题，理论请仔细查看feign-httpclien

**Comment by SoftwareKing** [comment] 2018-07-12 13:12
@qianglu1989 我要的就是开启压缩，这个问题官方代码已经fix了

**Comment by qianglu1989** [comment] 2018-07-12 13:13
当然你添加jar 也可以解决
  <dependency>
      <groupId>io.github.openfeign</groupId>
      <artifactId>feign-httpclient</artifactId>
    </dependency>
