### ISSUE TITLE
Get URL Calling by sending Encoded XML format in URL

### ISSUE THREAD

**Issue by dnyaneshwarjadhav** [spring-cloud/spring-cloud-openfeign#651] opened 2021-12-23 11:11 UTC
**Describe the bug**
I am using `org.springframework.cloud:spring-cloud-starter-openfeign:3.0.3` version for Feign client. trying to create `GetMapping` and send XML as encoded format in `QueryParameter`. but the server does not accept this encoded XML Format 

**Sample**
My Code is
```
//@Headers({"Content-Type: application/xml"})
    //@Headers("Content-Type: application/x-www-form-urlencoded")
    @Headers({"Content-Type: application/json"})
    @GetMapping(value = "/abc.dll")
    ResponseEntity<String> serviceCall(@RequestParam(name = "API") String api, @RequestParam(name = "XML") String XML);.
```

Ideally it is constructing some what like below
https://secure.abc.com/abc.dll?API=Verify&XML=%3CAddressValidateRequest%20USERID%3D%22023MBUSA5454%22%3E%3CRevision%3E1%3C/Revision%3E%3CAddress%3E%3CAddress1%3E1%20textile%20BENZ%20DR%3C/Address1%3E%3CAddress2%3E1%20textile%20BENZ%20DR%3C/Address2%3E%3CCity%3ESANDY%20SPRINGS%3C/City%3E%3CState%3EGA%3C/State%3E%3CZip5%3E30328%20-%204312%3C/Zip5%3E%3CZip4/%3E%3C/Address%3E%3C/AddressValidateRequest%3E

infact Feign client constructing similar URL but not giving proper response.
However the same URL tried from Browser and it is giving me actual required Output.

![image](https://user-images.githubusercontent.com/16952283/147232360-8e7cb7b1-1dec-4b16-8a53-a4cce4d939fa.png)

**Comment by OlgaMaciaszek** [comment] 2022-01-14 15:59
@dnyaneshwarjadhav thanks for submitting the issue. 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2022-02-04 01:06
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-02-04 01:06 UTC
Labels: waiting for feedback
