### ISSUE TITLE
JSON parse error: java.time.format.DateTimeParseException [Spring Boot - Feign Client]

### ISSUE THREAD

**Issue by zoroglu** [spring-cloud/spring-cloud-openfeign#888] opened 2023-08-25 16:09 UTC
When I make a request to a service containing `java.util.Date` with FeignClient, I get this error: `org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: java.time.format.DateTimeParseException: Text '1692738000000' could not be parsed at index 0`

**My dto:**
```
public class InputDto {
    private Date startDate;
    private Date endDate;
}
```

**FeignClient service:**

```
@PostMapping(value = {"/searchFile"}, produces = {MediaType.APPLICATION_JSON_VALUE})
ResponseEntity<ServiceResponse<List<FileDto>>> searchFile(@RequestBody InputDto searchDto);
```

```
<spring-boot.version>2.7.4</spring-boot.version>
<spring-cloud-starter-openfeign.version>3.1.5</spring-cloud-starter-openfeign.version>
```

If I define my variables as `java.time.LocalDate` I don't get an error. why does this problem occur?

**Comment by OlgaMaciaszek** [comment] 2023-12-14 13:32
Hello @zoroglu. I was not able to reproduce this issue (see a [working sample](https://github.com/OlgaMaciaszek/feign-eureka/tree/input-date)).  
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2023-12-21 13:34
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-12-28 13:34
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-12-28 13:34 UTC
Labels: waiting for feedback, feedback-reminder
