### ISSUE TITLE
Feign client doesn't serialize java.time.LocalDate's correctly while it present as object field

### ISSUE THREAD

**Issue by DmitriiVashchenko** [spring-cloud/spring-cloud-openfeign#573] opened 2021-07-08 15:35 UTC
I'm using Spring boot 2.4.5, Spring Cloud 2020.0.3, Java 11.
Is there a way to use a Feign client accepting a `java.time.LocalDate` as an object field where it is supposed to comply with a given format like `@DateTimeFormat` with some specific pattern?
For instance, I have the next object which I wanna represent as query params:

    @AllArgsConstructor
    public class QueryRequestParams {
        @DateTimeFormat(pattern = "dd.MM.yyyy")
        private LocalDate from;
        @DateTimeFormat(pattern = "dd.MM.yyyy")
        private LocalDate to;
    }

The instance of QueryRequestParams  looks like:

    new QueryRequestParams(LocalDate.parse("2011-12-03"), LocalDate.parse("2011-12-05"))

The feign client is:
   
    @FeignClient(url = "http://localhost:9000")
    public interface ExampleFeignClient {
        @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
        List<Object> getObjects(@SpringQueryMap QueryRequestParams queryRequestParams);
    }
`
When feign client does request and `QueryRequestParams` object has no null values the request look like as "http://localhost:9000?from=2011-12-03&to=2011-12-05" which has another format rather than I configured via DateTimeFormat annotation.

When I tried to use @DateTimeFormat with @RequestParam annotation just in ExampleFeignClient, for example:

    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
        List<Object> getObjects(@RequestParam("from") @DateTimeFormat(pattern = "dd.MM.yyyy") LocalDate from,
                                @RequestParam("to") @DateTimeFormat(pattern = "dd.MM.yyyy") LocalDate to);

then it works as I expected.
It there a way to use `@SpringQueryMap` with object which contains `LocalDate` field and that is formatted via `@DateTimeFormat(pattern = "dd.MM.yyyy")` annotation?
Thanks for any help!

**Comment by cbezmen** [comment] 2021-07-09 11:47
Hi @DmitriiVashchenko,

I think your expectation works on newer version of feign. I'm using Spring boot 2.5.2, Spring Cloud 2020.0.3, Java 11.

```java
@SpringBootApplication
@EnableFeignClients
@Slf4j
public class FeignCanApplication {

    public static void main(String[] args) {
        SpringApplication.run(FeignCanApplication.class, args);
    }

    @Autowired
    private TestClient testClient;

    @Bean
    public ApplicationRunner test() {
        return args -> {
            List<LocalDate> dateList = testClient.getObjects(new QueryRequestParams(LocalDate.parse("2011-12-03"), LocalDate.parse("2011-12-05")));
            log.info("{}", dateList);
        };
    }

    @FeignClient(name = "test", url = "http://localhost:8080")
    public interface TestClient {
        @GetMapping(value = "/get-data", produces = MediaType.APPLICATION_JSON_VALUE)
        List<LocalDate> getObjects(@SpringQueryMap QueryRequestParams queryRequestParams);
    }


    @RestController
    @Slf4j
    public static class TestController {

        @GetMapping(value = "/get-data", produces = MediaType.APPLICATION_JSON_VALUE)
        List<LocalDate> getObjects(@RequestParam("from") @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate from,
                                   @RequestParam("to") @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate to) {
            log.info("{} {}", from, to);
            return Arrays.asList(from, to);
        }
    }

    @AllArgsConstructor
    @Data
    public class QueryRequestParams {
        @DateTimeFormat(pattern = "dd.MM.yyyy")
        private LocalDate from;
        @DateTimeFormat(pattern = "dd.MM.yyyy")
        private LocalDate to;
    }
}
```
If I am wrong in somewhere, please share small code block so I can try to help more.

**Comment by DmitriiVashchenko** [comment] 2021-07-11 18:54
Hi @cbezmen, but your date formation is also different from the pattern. I expect the date to be shaped like dd.MM.yyy when this date field is represented as an object field and I using this like:

    public class QueryRequestParams {
        @DateTimeFormat(pattern = "dd.MM.yyyy")
        private LocalDate from;
        @DateTimeFormat(pattern = "dd.MM.yyyy")
        private LocalDate to;
    }

    @FeignClient(name = "test", url = "http://localhost:8080")
    public interface TestClient {
        @GetMapping(value = "/get-data", produces = MediaType.APPLICATION_JSON_VALUE)
        List<LocalDate> getObjects(@SpringQueryMap QueryRequestParams queryRequestParams);
    }

**Comment by cbezmen** [comment] 2021-07-13 07:08
Hi @DmitriiVashchenko 

I think it is not spring-open-feign problem.

`DateTimeFormat.ISO`only supports: 
* DATE
* TIME
* DATE_TIME
* NONE

You can add custom conversion service. Please check this link https://www.baeldung.com/spring-date-parameters

**Comment by DmitriiVashchenko** [comment] 2021-07-13 08:16
@cbezmen, but this way works fine

    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    List<Object> getObjects(@RequestParam("from") @DateTimeFormat(pattern = "dd.MM.yyyy") LocalDate from,
                            @RequestParam("to") @DateTimeFormat(pattern = "dd.MM.yyyy") LocalDate to);
Here also @DateTimeFormat annotation with LocalDate type, just presented as separate param, not field of object

**Comment by cbezmen** [comment] 2021-07-26 10:44
Hi @DmitriiVashchenko,

QueryRequestParams is also fail with `dd.MM.yyyy` because it is not a valid pattern. When you call it with wrong pattern it will throw DateTimeParseException. You have to send supported patterns of DateTimeFormat.ISO.

```java
public class QueryRequestParams {
    @DateTimeFormat(pattern = "dd.MM.yyyy")
    private LocalDate from;
    @DateTimeFormat(pattern = "dd.MM.yyyy")
    private LocalDate to;
}

new QueryRequestParams(LocalDate.parse("13-12-2011"), LocalDate.parse("12-05-2011")) // this will throw DateTimeParseException
```

**Comment by OlgaMaciaszek** [comment] 2021-07-26 15:50
@DmitriiVashchenko, @cbezmen is right - this will indeed throw an exception.

**Comment by spring-cloud-issues** [comment] 2021-08-02 15:54
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-08-09 15:54
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by FrischTag** [comment] 2022-01-06 09:44
I have the same problem with ZonedDateTime
I have a parameter 
```
  @DateTimeFormat(pattern = "yyyyMMdd'T'HHmmss'Z'")
  private ZonedDateTime scheduledFrom;
```

When I declare the param as direct method param
```
  @GetMapping(value = "/example")
  Map<String, Object> example(@RequestParam @DateTimeFormat(pattern = "yyyyMMdd'T'HHmmss'Z'") ZonedDateTime scheduledFrom);
``` 

the formatting works OK: 
```scheduledFrom=20220104T070640Z```


However when I try using this param as a part of nested object among with  @SpringQueryMap annotation
```
  public class WrappedScheduledFrom {
    @DateTimeFormat(pattern = "yyyyMMdd'T'HHmmss'Z'")
    private ZonedDateTime scheduledFrom;
  }
 
  @GetMapping(value = "/example")
  Map<String, Object> example(@SpringQueryMap WrappedScheduledFrom requestDto);
```
The formatting stops working:
```scheduledFrom=2022-01-04T07:06:40Z[UTC]```

**Comment by k0mmsussert0d** [comment] 2022-03-29 15:04
I don't understand why has this issue been closed. What kind of feedback was expected to be provided?

From my side, I can confirm that `@DateTimeFormat(pattern = "..."` on `@SpringQueryMap`-annotated parameter is ignored by the client and resulting request consists of default ISO date format, as if `@DateTimeFormat(iso = DateTimeFormat.ISO.DATE)` was given.

**Comment by OlgaMaciaszek** [comment] 2022-03-29 15:06
Will take a look at it.

**Comment by velykov** [comment] 2022-05-25 02:14
I can also confirm, that feign send date as array [2022, 05, 25] when I use LocalDate in body's object with MediaType.MULTIPART_FORM_DATA_VALUE, for example:

```
@FeignClient(name = "api-client", url = "${base-url}/api", configuration = ApiConfig.class)
public interface EdoApiClient {
    @PostMapping(value = "/documents/draft", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    DocumentResponse createDraft(DocumentRequest request);
}

@Getter
@Setter
public class DocumentRequest {
    private String name;
    private MultipartFile documentFile;
    private LocalDate documentDate;
}

public class ApiConfig {
    @Bean
    public Logger.Level feignLoggerLevel() {
        return Logger.Level.FULL;
    }
}

```

**Comment by OlgaMaciaszek** [comment] 2023-03-09 13:54
@FrischTag @k0mmsussert0d @velykov  - sorry for not getting back to you earlier - we were concentrating on the AOT/ native, jakarta and observability portfolio-wide efforts towards the end of 2022. If you would like us to take a closer look at it, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue as a link to a repo to a small executable app or tests that reproduce the issue rather than separate code snippets.

**Comment by spring-cloud-issues** [comment] 2023-03-16 13:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Closed** 2023-03-23 13:57 UTC
Labels: waiting for feedback, feedback-reminder
