### ISSUE TITLE
produces application/octet-stream  Io error help

### ISSUE THREAD

**Issue by lnsane** [spring-cloud/spring-cloud-openfeign#524] opened 2021-04-09 12:57 UTC
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

```java
 @GetMapping(value = ApiConst.UpcController.downloadTemplate.PATH,
            consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE,
            produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
    ResponseEntity<StreamingResponseBody> downloadTemplate()
```

error here 

```java
	@SuppressWarnings("ConstantConditions")
	public boolean hasEmptyMessageBody() throws IOException {
		InputStream body = this.response.getBody();
		// Per contract body shouldn't be null, but check anyway..
		if (body == null) {
			return true;
		}
		if (body.markSupported()) {
			body.mark(1);
			if (body.read() == -1) {
				return true;
			}
			else {
				body.reset();
				return false;
			}
		}
		else {
			this.pushbackInputStream = new PushbackInputStream(body);
			int b = this.pushbackInputStream.read();
			if (b == -1) {
				return true;
			}
			else {
				this.pushbackInputStream.unread(b);
				return false;
			}
		}
	}
```

this.pushbackInputStream.read()  Method threw 'java.io.IOException' exception.
stream is closed

why ? 
feign is not spport produces application/octet-stream  ?

**Comment by OlgaMaciaszek** [comment] 2021-04-16 10:08
Hello @lnsane, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-04-23 10:12
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-04-30 10:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-04-30 10:12 UTC
Labels: feedback-reminder, waiting for feedback
