### ISSUE TITLE
Data conversion timeout

### ISSUE THREAD

**Issue by ycy1991** [spring-cloud/spring-cloud-openfeign#187] opened 2019-05-24 03:26 UTC
Question
Transform data request timeout, use Response to receive everything normal
my code is:
the request is ok when return Response
![image](https://user-images.githubusercontent.com/16506338/58300792-97a40580-7e16-11e9-9ca8-e415948c80f5.png)
the quest return timed-out and no fallback available
![image](https://user-images.githubusercontent.com/16506338/58300764-7f33eb00-7e16-11e9-81fc-8fa5dbb551f7.png)

**Comment by ryanjbaxter** [comment] 2019-06-03 15:58
Please provide a better description of the problem.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-06-10 16:01
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-17 16:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-17 16:02 UTC
Labels: feedback-reminder, waiting for feedback
