### ISSUE TITLE
The combination of completableFuture.supplyAsync and openfeign cannot return results.

### ISSUE THREAD

**Issue by impactCn** [spring-cloud/spring-cloud-openfeign#638] opened 2021-12-04 08:37 UTC
current version:
```java
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>
```

```java
private CompletableFuture<ResultBase<List<UserDeviceInfoRes>>> airCleanOfUser() {
        return CompletableFuture.supplyAsync(() -> airCleanerFeign.user());
    }

    private CompletableFuture<ResultBase<List<UserDeviceInfoRes>>> footMachineOfUser() {
        return CompletableFuture.supplyAsync(() -> footMachineFeign.user());
    }
System.err.println(airCleanOfUser().get().getData());
System.err.println(footMachineOfUser().get().getData());
```

Such writing cannot return normally.
Even delaying the main thread will not work.
But,
```java
private CompletableFuture<ResultBase<List<UserDeviceInfoRes>>> airCleanOfUser() {
        return CompletableFuture.completedFuture(airCleanerFeign.user());
    }

    private CompletableFuture<ResultBase<List<UserDeviceInfoRes>>> footMachineOfUser() {
        return CompletableFuture.completedFuture(footMachineFeign.user());
    }
System.err.println(airCleanOfUser().get().getData());
System.err.println(footMachineOfUser().get().getData());
```
Can return.

It is different from what I imagined, what version can support
completableFuture.supplyAsync or method.
Thank~

**Comment by OlgaMaciaszek** [comment] 2021-12-08 14:56
Hello, @impactCn, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-12-15 15:00
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by impactCn** [comment] 2021-12-16 04:12
```java
@FeignClient(name = "service-name")
public interface WifiFeign extends WifiDeviceFeign {
    @PostMapping("wifiInfo")
    ResultBase<List<WifiDeviceInfoRes>> wifiInfo();
}

@RestController
@RequestMapping("device")
public class DeviceController {

    @Autowired
    private WifiFeign  feign;

    @PostMapping("wifiInfo")
    public ResultBase wifiInfo() {
        try {
            return task().get();
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        } finally {
            return null;
        }
    }

    private CompletableFuture<ResultBase<List<WifiDeviceInfoRes>>> task() {
        RequestContextHolder.setRequestAttributes(RequestContextHolder.getRequestAttributes(), true);
        return CompletableFuture.supplyAsync(() -> feign.wifiInfo());
    }
}

```

**Comment by OlgaMaciaszek** [comment] 2021-12-23 10:03
@impactCn  Please provide a sample as a link to a GitHub project that can be run and verified by us, without us having to add demo code to make the sample compile.

**Comment by spring-cloud-issues** [comment] 2022-02-04 01:06
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-02-04 01:06 UTC
Labels: waiting for feedback
