### ISSUE TITLE
The abuse of declarative call in Feigin

### ISSUE THREAD

**Issue by Shadowell** [spring-cloud/spring-cloud-openfeign#37] opened 2018-06-24 15:57 UTC
I have trouble for the following scenarios:
I have developed a job - service , and a flume - agent - service with spring boot. Now, I separately to deploy the same flume-agent-service in the five machines . The name of this same five micro service  is same, just deployed on different machines.And job - service will call the five services by  some rules  not by default loadbalance of Ribbon (for 
example,Just call the flume-agent-service which deployed on machine 1,machine 3 and machine 5). In this case, i have to write a heap of same interface which annotate which @FeignClient，and the code have to be modified when the number of flume-agent-service changed.

Can I only use restTemplate for this scenario?
Does Feign offer a solution to the above scenario?

Sincerely await your reply
Thank you !

**Comment by ryanjbaxter** [comment] 2018-06-25 18:40
I am not sure I understand exactly what the problem is.  Maybe if you provide an example it might be clearer.

**Comment by spencergibb** [comment] 2018-10-01 23:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-10-01 23:02 UTC
Labels: waiting for feedback
