### ISSUE TITLE
Matrix variable issue

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-openfeign#334] opened 2020-05-06 12:25 UTC
This leads on fom https://github.com/spring-cloud/spring-cloud-openfeign/issues/307, and I'm using Hoxton.SR4

I'm a bit confused by matrix variale resolution. Having the definition:

    @GetMapping(value = "/accounts{matrixVars}")
    AccountList getAccounts(@MatrixVariable("matrixVars") Map<String, List<String>> matrixVars);

results in the following if passing in the map [host:accounta, enabled:true]:
```
/accounts%3Bhostname%3D%5Baccounta%5D%3Benabled%3D%5Btrue%5D%
```
Rather than
```
/accounts;hostname=accounta;enabled=true
```
The encoding of semi-colons and equals makes the request fail.

**Comment by OlgaMaciaszek** [comment] 2020-06-05 15:10
@nickcodefresh Can you provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue (also containing the server-side endpoint for your feign client method and the arguments you call the feign client method with)?

**Comment by spring-issuemaster** [comment] 2020-06-12 15:10
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-06-19 15:10
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-06-19 15:10 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by nickcodefresh** [comment] 2020-08-17 16:10
Apologies for the delay but I've finally found time to be able to create a sample project. New ticket raised as https://github.com/spring-cloud/spring-cloud-openfeign/issues/395.
