### ISSUE TITLE
Fallbackfactory should be called only once after retry attempts are complete

### ISSUE THREAD

**Issue by rajakumare1** [spring-cloud/spring-cloud-openfeign#885] opened 2023-08-17 15:42 UTC
**Describe the bug**
I am currently using `SpringCloudOpenFeign` with  Fallback factory and Resillence4j Circuit Breaker and Resillience4j Retry
We are seeing that the Spring fallback factory  and fallback is invoked for before each retry attempt.
We want the fallback to happen only once after all the resillence4j retry attempts
How do we do this?

Below TestFallBackWithFactory is getting called before each of the resillence4j retry. How do stop it and call TestFallBackWithFactory only after retry attempts are meet. Please advise

**Sample**
```
@FeignClient(name = "test",
        url = baseURI",
        configuration = {ConfigTest.class},
        fallbackFactory = TestFallBackFactory.class)

public interface Test {
@RequestMapping(...)
ResponseEntity<Void> test (....)
}
```

```
@Component
class TestFallBackFactory implements FallbackFactory<> {
@Override
public TestFallBackWithFactory create() {
return new TestFallBackWithFactory(cause);
}

class TestWithFactory implements Test {
test() {}

}
```

**Comment by OlgaMaciaszek** [comment] 2023-12-15 11:55
Hello @rajakumare1, thanks for submitting the issue. 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue - as a link to a GH repo to a small executable app with all the required dependencies.

**Comment by spring-cloud-issues** [comment] 2023-12-22 11:59
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-12-29 11:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-12-29 11:59 UTC
Labels: waiting for feedback, feedback-reminder
