### ISSUE TITLE
Spring Data Pageable is not working alongside with @RequestBody param

### ISSUE THREAD

**Issue by vlsidlyarevich** [spring-cloud/spring-cloud-openfeign#147] opened 2019-03-13 10:59 UTC
Hello! 

I am using Feign as Rest client between my microservices, and i've discovered that Spring Data `Pageable` is not handled when used alongside with `@RequestBody` annotated objects.
Here is my Feign client method:
```java
    @PostMapping("api/v1/blockchain/addresses/balance/paged")
    Page<AddressBalanceResponse> getAddressesBalance(@RequestBody List<String> addresses, Pageable pageable);
```
But in cases when `@RequestBody` is not used, for example `@RequestParam` used instead, `Pageable` works well.

Spring cloud version: Greenwich.SR1
Spring boot parent version: 2.1.3.RELEASE

**Comment by ryanjbaxter** [comment] 2019-03-19 20:04
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-03-26 20:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-04-02 20:05
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-04-02 20:05 UTC
Labels: feedback-reminder, waiting for feedback
