### ISSUE TITLE
Feign Inheritance has conflicts with fallback classs When the @RequstMapping appears on the class header。

### ISSUE THREAD

**Issue by munan56** [spring-cloud/spring-cloud-openfeign#566] opened 2021-06-30 09:40 UTC
**Describe the bug**
Feign Inheritance has conflicts with fallback classs When the @RequstMapping appears on the class header。

It will be caused exception
```
Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'com.gitee.helloworlddemo.openfeign.consumer.resilience4j.client.SecondClinet' method 
*.SecondClinet#hello()
```

```
@FeignClient(url = "${second.url}", name = "secondClient", fallback = SecondFallBack.class)
@RequestMapping("/api/second")
public interface SecondClinet {

    @RequestMapping("/hello")
    String hello();
}
```

It's normal
```
@FeignClient(url = "${second.url}", name = "secondApi", fallback = SecondFallBack.class)
public interface SecondClinet {

    @RequestMapping("/api/second/hello")
    String hello();


}

```

I think both of these should be running fine.

**Comment by munan56** [comment] 2021-07-01 03:19
When @RequestMapping is on the interface, he considers feignclient to be a handle. This means that both the fallback class and feignclient are used as handlers. is this normal?

**Comment by munan56** [comment] 2021-07-01 03:22
> When @RequestMapping is on the interface, he considers feignclient to be a handle. This means that both the fallback class and feignclient are used as handlers. is this normal?

![image](https://user-images.githubusercontent.com/28220817/124059795-47201d00-da5e-11eb-989b-0f340b74dca7.png)
I know how to solve it (rewrite isHandlefang), but is this kind of problem normal?

**Comment by cbezmen** [comment] 2021-07-01 06:09
I think it is Duplicate of #564 . Please check #564

**Comment by munan56** [comment] 2021-07-01 09:47
> I think it is Duplicate of #564 . Please check #564

sorry，I will close the issue.

**Closed** 2021-07-01 09:47 UTC
Labels: waiting-for-triage
