### ISSUE TITLE
Feign client returns empty response body, when http code is 401

### ISSUE THREAD

**Issue by nada-gamal** [spring-cloud/spring-cloud-openfeign#506] opened 2021-03-10 18:54 UTC
FeignClient return an empty response body (response.body()) whenever the response status code is 401. 
I have did a direct call to the server through postman and the response is returning as expected with proper body. So no problem on server side.

I have also tried `ApacheHttpClient` as well as `OkHttpClient` and still the issue exits.

Version used:
JDK 11, openfeign 2.2.6

You can find below snapshots of the dependencies I am using as well as configuration:
```
         <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-okhttp</artifactId>
        </dependency>
```

```
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000
        loggerLevel: NONE
```

**Comment by evgenijbogdanov** [comment] 2021-03-25 08:27
In my case I solved this problem by adding this dependencies:

`    implementation platform("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation group: 'io.github.openfeign', name: 'feign-okhttp', version: '11.1'`

Then, I created a config class for client, where set a bean of OkHttpClient:

`public class ClientConfiguration {

    @Bean
    public ErrorDecoder errorDecoder() {
        return new CustomWebClientErrorDecoder();
    }

    @Bean
    public OkHttpClient client() {
        return new OkHttpClient();
    }
}
`

Finally, I set this config class as "Configuration" in @FeignClient annotation:

`@FeignClient(value = "webclient" configuration = ClientConfiguration.class)
public interface WebClient {`

**Comment by nada-gamal** [comment] 2021-03-25 18:17
@evgenijbogdanov I tried this way and still didn't work

**Comment by OlgaMaciaszek** [comment] 2021-04-12 12:12
Hello, @nada-gamal, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue - will take a look.

**Comment by spring-cloud-issues** [comment] 2021-04-19 12:17
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-04-26 12:17
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by ariady-putra** [comment] 2023-07-06 03:39
2023 and this still happens

**Comment by OlgaMaciaszek** [comment] 2023-07-06 10:27
@ariady-putra please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2023-07-13 10:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-07-20 10:30
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by ulpcan** [comment] 2023-09-05 11:43
This problem continues

**Comment by OlgaMaciaszek** [comment] 2024-01-08 13:01
@ulpcan if you want us to look at the issue, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue, as a link to a GitHub repo with a sample app or tests.

**Comment by ulpcan** [comment] 2024-01-08 13:23
It is very obvious that you get null body response when http code is 401. There is no further needed information.

Go write Feign configuration, send http request with it. If you get 401 from anywhere, anytime you will see at the debugger feign decoder reponse' is always null

**Comment by ulpcan** [comment] 2024-01-08 13:24
> Hello, @ulpcan, have you found a solution for response body empty (401 error)?

Nope sorry

**Comment by gokulkalagara** [comment] 2024-01-09 12:46
### To Resolve this empty response body for 401 

**Need to add extra dependency feign-httpclient**

```
<dependency>
  <groupId>io.github.openfeign</groupId>
  <artifactId>feign-httpclient</artifactId>
</dependency>
```

> When you are running in debug mode, while reading response body, if it throws an java.io.IOException: the stream is closed in **ErrorDecoder**

please disable toString() option in Intellij 

> Preferences | Build, Execution, Deployment | Debugger | Data Views | Java

![Screenshot 2024-01-09 at 5 56 25 PM](https://github.com/spring-cloud/spring-cloud-openfeign/assets/13214923/d7876aff-5750-4c44-a16a-c02b650bb772)

**Comment by OlgaMaciaszek** [comment] 2024-01-18 13:37
This is done [here](https://github.com/OpenFeign/feign/blob/cfcdbd15d6904cc0dfa39097d8e9921c2fdae924/core/src/main/java/feign/Client.java#L131-L136), within the core Feign library implementation. This is not part of the Spring Cloud OpenFeign project, which just adds additional functionality and integrations on top of that third-party library. If you would like someone to look at this issue, please report it in the [OpenFeign/feign](https://github.com/OpenFeign/feign) repository.

**Closed by OlgaMaciaszek** 2024-01-18 13:37 UTC
Labels: closeable

**Comment by stefan-g** [comment] 2024-07-04 08:16
@gokulkalagara I'm facing the same problem that the response in the error decoder contains an empty body but the suggested solution does not work. My problem is that i'm using spring cloud Netflix and ApacheHttpClient doesn't seems to be able to automatically resolve the loadbalance url into the real url. any solution to fix this problem?

**Comment by OlgaMaciaszek** [comment] 2024-07-04 08:31
@stefan-g are you also facing the problem only in your docker environment or also locally?

**Comment by stefan-g** [comment] 2024-07-04 09:01
@OlgaMaciaszek currently i'm testing it locally (docker is not used).
I'm getting an java.net.UnknownHostException because the service id is not resolved to the actual url (It does work when i don't define ApacheHttpClient as a bean).

i tried it with and without @LoadBalanced but with not difference.

  @Bean
  //@LoadBalanced
  public Client feignClient() {
    return new ApacheHttpClient();
  }

should the service id be resolved automatically?

**Comment by OlgaMaciaszek** [comment] 2024-07-04 09:20
@stefan-g  No, we do not support `@LoadBalanced Client`. You will find info on all the available integrations for Spring Cloud LoadBalancer in the [docs](https://docs.spring.io/spring-cloud-commons/reference/spring-cloud-commons/loadbalancer.html). For Feign Clients we integrate using `@FeignClient`  annotation by creating our own `Client` implementation and setting it up under the hood - you can see more details [here](https://docs.spring.io/spring-cloud-openfeign/reference/spring-cloud-openfeign.html#netflix-feign-starter).

**Comment by stefan-g** [comment] 2024-07-04 10:03
@OlgaMaciaszek  thanks for the links. that helped. 

the following settings fix the problem for me:

add the following dependency at the gradle.build
`    implementation 'io.github.openfeign:feign-hc5:13.3'`

and enable the feign-hc5 client for spring cloud in the application.yml:

```
spring:
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
```
